### PR TITLE
Update jenkins.sh

### PR DESCRIPTION
**Pull request by Nomad653**
Salam, Bootcamp 22 was here.
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dduportal** [comment]
Please do not use public projects for trying out pull requests.

**Comment by MarkEWaite** [comment]
Please advise the sponsors of your boot camp that they are doing a disservice to open source projects when they waste the time of open source maintainers with junk pull requests, junk issue reports, or other forms of junk communications.  

Junk submitted to open source projects also damages the credibility of the person submitting the pull request.  It may result in them being banned from the open source project.  I'm sure that the boot camp sponsors do not want to damage your credibility as part of their boot camp.  Help them understand that they need to specifically teach boot camp participants about the risk that junk submissions cause to personal credibility.  It would be sad if a boot camp that was trying to help you develop skills had the unintended result of damaging your credibility.

**Comment by Nomad653** [comment]
I hope this message finds you well. I am writing to express my sincere apologies for the recent junk pull request I submitted to your GitHub repository. I was unaware of the negative impact that such an action could have on your project, and I deeply regret any inconvenience or disruption that I may have caused.

In an effort to educate myself and prevent similar mistakes in the future, I have taken the time to research best practices for contributing to open-source projects. I now understand the importance of thoroughly reading and adhering to contribution guidelines and ensuring that my pull requests are meaningful and well-structured.

As a gesture of goodwill and my commitment to making amends, I would like to offer my assistance in resolving any issues that may have arisen as a result of my actions. If there are any tasks that you feel I could help with, please do not hesitate to reach out to me.

Once again, I deeply apologize for my mistake and any trouble it may have caused. I appreciate the hard work and dedication that goes into maintaining an open-source project like yours, and I am committed to being a more responsible and respectful contributor in the future.

Thank you for your understanding, and I hope you can accept my sincere apology.

Best regards,

Vusal Hasanli
Nomad653

**Comment by MarkEWaite** [comment]
Thanks for your kind comments @Nomad653 and thanks for being responsive.  We wish you all the best in your continuing journey contributing to open source.  Best of luck with the boot camp.  No further action is needed from you at all.  Share the word that open source is a good thing and that when many people help a little, it can result in great things.

**Pull request closed without merging**
