### PR TITLE
Make Dockerfile Indentation Consistent

### PR DESCRIPTION
**Pull request by amayer5125**
Make `RUN` command block indentation consistent throughout all Dockerfiles

### CODE REVIEW

**Comment by amayer5125** [comment]
The Dockerfiles indentation is not consistent. In **Dockerfile** [lines 37-41](https://github.com/jenkinsci/docker/blob/master/Dockerfile#L37-L41) and [line 58](https://github.com/jenkinsci/docker/blob/master/Dockerfile#L58) use 2 spaces for indentation. In **Dockerfile-alpine** [line 48](https://github.com/jenkinsci/docker/blob/master/Dockerfile-alpine#L48) uses 2 spaces for indentation. In **Dockerfile-slim** [lines 37-41](https://github.com/jenkinsci/docker/blob/master/Dockerfile-slim#L37-L41) and [line 58](https://github.com/jenkinsci/docker/blob/master/Dockerfile-slim#L58) use 2 spaces for indentation.

This merge requests changes all indented blocks of code inside of Dockerfiles to also use 2 spaces instead of 4 spaces.

**Comment by batmat** [comment]
> The Dockerfiles indentation is not consistent. In Dockerfile lines 37-41 and line 58 use 2 spaces for indentation. In Dockerfile-alpine line 48 uses 2 spaces for indentation. In Dockerfile-slim lines 37-41 and line 58 use 2 spaces for indentation.

I'm even more confused now. You're telling things are inconsistent, and write everything is indented with 2 spaces, which seems pretty consistent...

**Comment by amayer5125** [comment]
@batmat Sorry I had just woken up when I typed that. All the lines I listed in my last comment use 2 spaces. The lines changed in this PR go from 4 spaces to 2 spaces. They are different lines.

**Comment by amayer5125** [comment]
For example in **Dockerfile** [lines 20-22](https://github.com/jenkinsci/docker/blob/master/Dockerfile#L20-L22) use 4 spaces. In **Dockerfile-slim** [lines 20-22](https://github.com/jenkinsci/docker/blob/master/Dockerfile-slim#L20-L22) also uses 4 spaces.

**Pull request merged**
