### PR TITLE
feat: :sparkles: Install tzdata for update timezone changes

### PR DESCRIPTION
**Pull request by mohammaddehnavi**
According to [this link!](https://mm.icann.org/pipermail/tz-announce/2022-August/000071.html) there is some change in other country time zone info and it's good to update timezone info in every build

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
Seems reasonable to me.  The Jenkins controller in the container image is willing to display information in local time zones, so it probably should have the most recent definition of those time zones.

Are you willing to make the same change for the rest of the containers in the repository?  Alpine seems to already include tzdata, but the other containers do not.

**Comment by mohammaddehnavi** [comment]
> Seems reasonable to me. The Jenkins controller in the container image is willing to display information in local time zones, so it probably should have the most recent definition of those time zones.
> 
> Are you willing to make the same change for the rest of the containers in the repository? Alpine seems to already include tzdata, but the other containers do not.

Hello dear @MarkEWaite 
I appreciate your consideration and also added the tzdata package in all Dockerfile.

**Review by dduportal — APPROVED** [review]
That looks like a great idea, thanks for contributing!

**Comment by dduportal** [comment]
As we are 2 maintains whom approved this change, I'll proceed for merging.

Please note that this change will only be visible:

- On the next weekly release, the 11 of July for the 2.414 version
- On the next LTS release (I'm not sure about the datetime, most probably in 1 to 3 weeks)

**Pull request merged**
