### PR TITLE
add ENV for JENKINS_USER and JENKINS_UID

### PR DESCRIPTION
**Pull request by vvitayau**

### CODE REVIEW

**Comment by carlossg** [comment]
Hi @vvitayau, these changes don't really have any effect as the permissions are set at build time, so you can't use the env vars at runtime to change the jenkins_user permissions for instance (that can be done with `docker run -u` anyway)

**Comment by vvitayau** [comment]
I agree with your comment, 
however this PR is to ease other organization who may need to customize
since they may not have be running

```
uid=1000(jenkins) gid=1000(jenkins) groups=1000(jenkins)
```

Centralizing where to modify is easier than having to comb each line to change.

**Comment by vvitayau** [comment]
FIgured an awkward workaround to extend existing Dockerfile.
It involves toggling user before/after fix the uid for jenkins as well as a required repeat chown
```
FROM jenkins:1.609.2

USER root

# was uid=1000(jenkins) 
ENV JENKINS_UID 10001

# now uid=10001(jenkins)
RUN usermod --uid $JENKINS_UID $JENKINS_USER

#VOLUME $JENKINS_HOME
RUN chown -R $JENKINS_USER "$JENKINS_HOME" /usr/share/jenkins/ref

USER $JENKINS_USER

# list of jenkins plugins to install
COPY plugins.txt /usr/share/jenkins/ref/

# download jenkins plugins from JENKINS_UC
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt

# uncomment to experiment local plugins, fetch via curl, etc.
#ADD *.?pi /usr/share/jenkins/ref/plugins/

# additional groovy scripts to be executed on startup
COPY *.groovy /usr/share/jenkins/ref/init.groovy.d/
```

**Comment by ndeloof** [comment]
You should not need to override USER, even with bind mounted jenkins_home (which is the expected setup). A better approach is to rely on a data volume container

**Pull request closed without merging**
