### PR TITLE
Enable Docker deployments for the experimental branch

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This is an experimental branch for fixing the deployments to jenkins4eval. Will continue later today

CC @imdurgadas @jmreicha @batmat

### CODE REVIEW

**Comment by imdurgadas** [comment]
@oleg-nenashev We will need to revisit this line: https://github.com/jenkinsci/docker/blob/master/Jenkinsfile#L52

We may also need to see what creds does the above line inject !

**Comment by oleg-nenashev** [comment]
Just to summarize the previous exploration... Credentials settings are fine on the DockerHub side:

jenkins4eval_perm


Credentials code is here: https://github.com/jenkins-infra/pipeline-library/blob/afe8616b181c86aba61cf761f90e194b2fe3d20a/vars/infra.groovy#L11-L21

And it is definitely not a ci.jenkins.io misconfiguration, because `jenkins4eval/jenkinsfile-runner` gets deployed correctly from https://github.com/jenkinsci/jenkinsfile-runner/blob/master/Jenkinsfile#L97--L120 . My assumption is that the credentials environment is not correctly passed to the manual Docker CLI invocation. It may happen due to the environment variable loss in Make or due to another issue

**Comment by jmreicha** [comment]
Hrm, interesting.  Wonder if running the build with debug turned on turns up any clues?  e.g. `./publish-experimental.sh -d` in the Makefile?

**Comment by oleg-nenashev** [comment]
> Hrm, interesting. Wonder if running the build with debug turned on turns up any clues? e.g. ./publish-experimental.sh -d in the Makefile?

Missed the comment. No clue. Looks like credentials got suppressed somewhere between script invocation layers. Not looking at it actively ATM

**Comment by jmreicha** [comment]
Should be easy enough to test.  I can test the change if you give me push access to the branch.

**Comment by slide** [comment]
This needs to have master merged in to pick up the fix

**Comment by slide** [comment]
@batmat The jenkins4eval branch needs master merged in to get the fix I did in the PR

**Comment by batmat** [comment]
@slide I restarted it because from the PR status link, it seemed that `pr-merge` was built hence should have automatically merged against "new" master?

**Comment by slide** [comment]
@batmat, isn't the pr against the jenkins4eval branch?

**Comment by slide** [comment]
Nm, my brain is not working. This or should build against master, you are correct.

**Comment by slide** [comment]
There seems to be some issue when doing a PR from a branch in the same repo (not a fork), the or-merge build doesn't happen. This occured on the repo permissions updater as well.

**Comment by lag-linaro** [comment]
Thanks for picking this back up @jmreicha.  Hopefully you guys can get this sorted.

**Comment by slide** [comment]
Can someone merge master into the jenkins4eval branch so the fix for the container build gets pulled in? For some reason, ci.j.o doesn't build PR's if the PR comes from a branch on the same repo.

**Comment by batmat** [comment]
done

**Comment by jmreicha** [comment]
@slide I'll try to get around to looking at it but won't have much time these next few weeks.

**Comment by slide** [comment]
@jmreicha The problem is that the branch is being built, not the pr-merge, so this actual pull request is not being built right now, just the branch. I am not sure why this is the case.

**Comment by slide** [comment]
The check in the Jenkinsfile for the jenkins4eval branch is already merged in. Do we need this PR anymore?

**Comment by slide** [comment]
@oleg-nenashev I think we can close this, the work has been merged into master at this point.

**Pull request closed without merging**
