### PR TITLE
Modify the UID of the jenkins user to match that of the mounted volume

### PR DESCRIPTION
**Pull request by elifarley**
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/docker/238)

### CODE REVIEW

**Comment by carlossg** [comment]
I'm not sure this is the right approach, running the container as root and then switch based on the filesystem?
does it even work? from a quick look it would seem that runs as jenkins but then tries to run usermod, which would require root

**Comment by elifarley** [comment]
Indeed, it's not even booting...

It's working perfectly in https://github.com/elifarley/docker-jenkins-uidfv, and I'm trying to make it work directly in the official Jenkins docker image.

**Comment by elifarley** [comment]
Ok, now it's working, after removing the last line (USER ${user}).

Here's how you can test it:
```
sudo chown 111:112 ~/data/jenkins-test
ls -Falkn ~/data/
drwxr-xr-x 12  111  112 4096 Abr  8 14:12 jenkins-test/

docker run --name jenkins-test -d -p 8081:8080 -v ~/data/jenkins-test:/var/jenkins_home quay.io/elifarley/alpine-jenkins:uid-from-volume

docker exec -it jenkins-test bash -l

root@d13f17be460c:/# id jenkins
uid=111(jenkins) gid=0(root) groups=0(root)
```

**Comment by svanoort** [comment]
I rigged up something like this recently; there's a bit more to do to ensure permissions play out correctly:

You can omit sudo-er within the container if desired (I find it helpful for a variety of things, since I use it for build/install inside container environments):

```bash
#!/bin/bash
# add_user.sh
# Sets up a user & group and runs as them within the container, adding them as a sudoer

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo 'Create user and group and switch to them'
    echo 'Arguments: are username userid groupname groupid'
    echo 'At least one is missing!'
    exit 1
else
    addgroup "$3" --gid "$4"
    useradd "$1" -m -u "$2" -g "$3"   # Omit the -m here, to avoid creating home directory for user.
    echo "$1 ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
    su $1 -s /bin/bash
fi
```

When you run, it needs to be something like this:
`as_user.sh $(id -un) $(id -u) $(id -gn) $(id -g)`

**Comment by elifarley** [comment]
@ svanoort I've been running Jenkins with this patch for a few weeks, and after some checks, permissions look correct.

I believe the as_user.sh (or add_user.sh) isn't needed.

**Comment by elifarley** [comment]
> I'm not sure this is the right approach, running the container as root and then switch based on the filesystem?
> does it even work? from a quick look it would seem that runs as jenkins but then tries to run usermod, which would require root
> 

In fact, once the container starts, the root user changes the UID of the **jenkins** user to match that of the owner of the mounted volume at **/var/jenkins_home**. After that, the root user becomes the **jenkins** user, which then runs *tini* (as the **jenkins** user).

If the owner of **/var/jenkins_home** is the same for all files and folders inside it, then the **jenkins** user inside the container will have no ownership-related problems when reading or writing to anything inside **/var/jenkins_home**, even though its user login inside the container is **jenkins** and outside it is something entirely different.

Can you please explain why that isn't the right approach?

**Comment by carlossg** [comment]
See #225 for comments about using gosu

Besides with this patch you can't `docker run -u jenkins jenkins` (the patch in #225 checks if already running as the expected user) as your image requires root to start. There are environments (like openshift) that don't allow launching containers as root

**Comment by ndeloof** [comment]
Docker will create a volume to match container user ID if you just let him do his job:
Typically `docker run -v jenkins_home:/var/jenkins_home ...` will create volume `jenkins_home` you can re-attach to another container when updating image, and ensure permissions are well set.

UID mismatch issue only happens if you force a bind mount from a host folder, then it's up to you to ensure permissions are well set.

**Comment by ndeloof** [comment]
:-1: on any requirement to run as `root`

**Comment by bdruemen** [comment]
I'm the author, sorry for being to busy to look at my own github projekt.
I thought that there would be a solution to mapping users between kernel namespaces soon, so this project eventually would have become obsolete.
There is a real problem underlining, not solved yet.
In our client projects we  have defined daemon to be the universal non-root user with her default user-id, which seems to be the same on every distribution.
But using only one user-id everywhere lowers security.

**Comment by ndeloof** [comment]
I'm also waiting for userId translation when using mounts inside container to help in file ownership/right management. Anyway using bind mount should be avoided, just use volume to get it right.

**Pull request closed without merging**
