### PR TITLE
Noting jenkins.install.UpgradeWizard.state

### PR DESCRIPTION
**Pull request by jglick**
Was useful in https://github.com/jenkinsci/workflow-aggregator-plugin/pull/5.

@reviewbybees esp. @kzantow

### CODE REVIEW

**Comment by kzantow** [comment]
:bee: x 💯

**Comment by carlossg** [comment]
:bee:

**Comment by carlossg** [comment]
@jglick is this still valid? my image asks for initial password and plugin setup anyway

**Comment by carlossg** [comment]
see https://github.com/jenkinsci/docker/issues/310

**Comment by simonvanderveldt** [comment]
As mentioned by @carlossg this doesn't work with the current image (2.7.4), not sure if it ever worked?

**Pull request merged**
