### PR TITLE
Update alpine to 2.60.3.

### PR DESCRIPTION
**Pull request by francois2metz**
Updated the alpine branch to be able to update the official jenkins images.

### CODE REVIEW

**Comment by carlossg** [comment]
alpine branch is no longer used, Dockerfile-alpine is

**Comment by francois2metz** [comment]
OK. Then we need to  find a way to be able to update the official alpine image. See https://github.com/docker-library/official-images/pull/3421

If I put the dockerfile in another folder, would you accept the change?

**Comment by carlossg** [comment]
The `jenkins` image has been deprecated in favor of `jenkins/jenkins`
I thought @ndeloof had talked to docker

**Comment by francois2metz** [comment]
Didn't knew about. Just updated my instance with `jenkins/jenkins` :).

**Comment by ndeloof** [comment]
Maybe we should just remove this obsolete branch now

**Pull request merged**
