### PR TITLE
Skip lines that start with #

### PR DESCRIPTION
**Pull request by moatazelmasry2**
Add the ability to comment out lines in plugin.txt

### CODE REVIEW

**Comment by carlossg** [comment]
can you add a test to https://github.com/jenkinsci/docker/blob/master/tests/install-plugins/pluginsfile/plugins.txt ?

**Comment by carlossg** [comment]
ping @moatazelmasry2

**Comment by moatazelmasry2** [comment]
Yes sorry about the delay. I'll get it done this week.

**Comment by carlossg** [comment]
done in #622

**Pull request closed without merging**
