### PR TITLE
Allow setting up of custom number of executors

### PR DESCRIPTION
**Pull request by hayderimran7**
The number of executors can be set via init.groovy file,
this allows changing the default num of executors from 2
whatever user specifies in init.groovy file.

Change-Id: I410ff043235d1dc9d5e1a72addd7669c2f2d5101

### CODE REVIEW

**Comment by carlossg** [comment]
I think that's good as documentation, but should not change the default number of Jenkins executors.

**Comment by carlossg** [comment]
could you rebase to just 1 commit? thanks

**Comment by hayderimran7** [comment]
@carlossg  Done :+1:

**Comment by carlossg** [comment]
Added with a slight change to add a new file and how to extend the image

**Pull request closed without merging**
