### PR TITLE
https://github.com/jenkinsci/docker/issues/1415

### PR DESCRIPTION
**Pull request by dduportal**
This PR should NOT be merged. It's only there to report and show the required content in order to correct #1415 .

Please note that https://github.com/jenkinsci/docker/blob/gh-1415/install-plugins.sh is present.

With the current change, a dry run show the following result:

```console
./.ci/publish.sh -n
Docker repository in Use:
* JENKINS_REPO: jenkins/jenkins
Dry run, will not publish images
latest_weekly_version=2.357
latest_lts_version=2.346.1
Version 2.329 higher than 1.0: publishing 2.329 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.330 higher than 1.0: publishing 2.330 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.331 higher than 1.0: publishing 2.331 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.332 higher than 1.0: publishing 2.332 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.332.1 higher than 1.0: publishing 2.332.1 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.332.2 higher than 1.0: publishing 2.332.2 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.332.3 higher than 1.0: publishing 2.332.3 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.332.4 higher than 1.0: publishing 2.332.4 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.333 higher than 1.0: publishing 2.333 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.334 higher than 1.0: publishing 2.334 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.335 higher than 1.0: publishing 2.335 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.336 higher than 1.0: publishing 2.336 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.337 higher than 1.0: publishing 2.337 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.338 higher than 1.0: publishing 2.338 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.339 higher than 1.0: publishing 2.339 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.340 higher than 1.0: publishing 2.340 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.341 higher than 1.0: publishing 2.341 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.342 higher than 1.0: publishing 2.342 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.343 higher than 1.0: publishing 2.343 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.344 higher than 1.0: publishing 2.344 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.345 higher than 1.0: publishing 2.345 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.346 higher than 1.0: publishing 2.346 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.346.1 higher than 1.0: publishing 2.346.1 latest_weekly:false latest_lts:true
docker buildx bake --file docker-bake.hcl linux
Version 2.347 higher than 1.0: publishing 2.347 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.348 higher than 1.0: publishing 2.348 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.349 higher than 1.0: publishing 2.349 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.350 higher than 1.0: publishing 2.350 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.354 higher than 1.0: publishing 2.354 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.355 higher than 1.0: publishing 2.355 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
Version 2.356 higher than 1.0: publishing 2.356 latest_weekly:false latest_lts:false
docker buildx bake --file docker-bake.hcl linux
```

### CODE REVIEW

**Comment by dduportal** [comment]
Ping @timja @MarkEWaite I'm waiting for a approval of this PR.

Once approved, I won't merge it, but I'll setup trusted.ci.jenkins.io to run a build of the source branch.

**Review by MarkEWaite — APPROVED** [review]
Looks good to me

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
- Test on my machine **before* the rebuild:

```console
➜  ~ docker pull jenkins/jenkins:2.332.1 && docker run --rm --entrypoint=cat jenkins/jenkins:2.332.1 /usr/local/bin/install-plugins.sh
2.332.1: Pulling from jenkins/jenkins
Digest: sha256:fc86feafd14d8b6e0342c776d59b3ad43537fde2fd020a4bbaa3eb68d4d151ae
Status: Image is up to date for jenkins/jenkins:2.332.1
docker.io/jenkins/jenkins:2.332.1
#!/bin/bash -eu

echo "WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli"
exit 1
```

- Branch `gh-1415` added to trusted.ci + build triggered

**Comment by dduportal** [comment]
- Build is currently running as expected and already re-deployed some versions.
- I got the command `docker pull jenkins/jenkins:2.332.1 && docker run --rm --entrypoint=cat jenkins/jenkins:2.332.1 /usr/local/bin/install-plugins.sh` which now show the `install-plugins.sh` script content with full old script.

**Comment by dduportal** [comment]
- Build finished with success
- All images were re-published until 2.356 included.

Closing the PR, tagging and deleting the branch

**Pull request closed without merging**
