### PR TITLE
Fix agent port configuration

### LINKED ISSUE #803: Set JENKINS_SLAVE_AGENT_PORT via java property
Atm, the port at which jenkins listens for connecting agents is set via this [script](../blob/master/init.groovy) and gets published at  
`JENKINS_URL/tcpSlaveAgentListener`.

If I probe this value shortly after startup, e.g. via:
```
watch -n 0.1 -d "wget --save-headers --output-document - localhost:8080/tcpSlaveAgentListener | grep JNLP"
```
,I noticed that the actual port number is at first set to a random number and then the script mentioned above causes the change to the desired value (e.g. 50000).

This can lead to unwanted timing issues, especially when related jenkins working agents are also packed in docker containers and started simultaneously. I therefore suggest to fix the port setting via [java system properties](https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties) which sets the correct values right from the start.

I successfully tried it by setting
```
JAVA_OPTS=-Djenkins.model.Jenkins.slaveAgentPort=50000 -Djenkins.model.Jenkins.slaveAgentPortEnforce=true
```
, but I think it would be better to implement this behaviour in the core image and not to eat up the `JAVA_OPTS` variable for this.

### PR DESCRIPTION
**Pull request by hpedrorodrigues**
**Issue**:

I'm using this docker image with [swarm-plugin][swarm-plugin], and I'm having some connection issues between them.

The Swarm Plugin always disconnects after a Jenkins restart, even when the [retry flags][swarm-plugin-properties] are set.

After investigating this, I've seen that the agent port number is first set to a [random value][agent-port-initial-value] and then the [groovy script][groovy-script] changes to the desired value in this image. Jenkins is started before this script execution, and when the plugin connects to `${JENKINS_URL}/tcpSlaveAgentListener/` the Jenkins server returns the random port in `X-Jenkins-JNLP-Port` and `X-Hudson-JNLP-Port` headers, what causes the problem.

**What this PR does**:

This PR sets the agent port using [system properties][system-properties], that set the right value since the start.

**Approach**:

If the environment variable `JENKINS_SLAVE_AGENT_PORT` is set and has some value, then the `jenkins.sh` script will add it as the value of `jenkins.model.Jenkins.slaveAgentPort` property in java options.

`jenkins.sh` script will only add the `jenkins.model.Jenkins.slaveAgentPort` property to `JAVA_OPTS` if it is not already added.

This PR also removes the `init.groovy` script because with this approach it won't be needed anymore.

**Which issue(s) this PR fixes**:

Fixes #803

**Notes**

If someone has any concerns or suggestions about this, please comment.

[swarm-plugin]: https://github.com/jenkinsci/swarm-plugin
[swarm-plugin-properties]: https://wiki.jenkins.io/display/JENKINS/Swarm+Plugin
[agent-port-initial-value]: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/Jenkins.java#L592
[groovy-script]: https://github.com/jenkinsci/docker/blob/master/init.groovy
[system-properties]: https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties

### CODE REVIEW

**Comment by hpedrorodrigues** [comment]
For now, I'm checking if the property `jenkins.model.Jenkins.slaveAgentPort` is passed from `JAVA_OPTS`.

**Comment by hpedrorodrigues** [comment]
Should I update README with this behavior?

**Comment by carlossg** [comment]
please

**Comment by hpedrorodrigues** [comment]
Readme updated

**Comment by hpedrorodrigues** [comment]
Readme updated. Also, Is it possible to add this to the next release?

**Pull request merged**
