### PR TITLE
-Duser.home=$JENKINS_HOME

### PR DESCRIPTION
**Pull request by jglick**
Works around [JENKINS-45755](https://issues.jenkins-ci.org/browse/JENKINS-45755), regardless of when https://github.com/jenkinsci/remoting/pull/197 is delivered. Otherwise [you get junk](https://stackoverflow.com/q/1503284/12916) if your UID is not right.

@reviewbybees esp. @oleg-nenashev & @carlossg

### CODE REVIEW

**Comment by jglick** [comment]
#566 should be considered also. The difference IIUC is that in the cases reported as problems, the `--user` of the image was not 1000 ~ `jenkins`, and so `/etc/passwd` had no entry for this UID, thus `?` rather than `/var/jenkins` as was passed to `useradd`.

**Comment by jglick** [comment]
Confirmed: the stock image works _already_ in case you use 1000 rather than 2000 for the `chown` and drop the `-u 2000`, using the default `USER`.

**Comment by jglick** [comment]
> Before passing this param you should ensure that it is not defined in `JAVA_OPTS` by the user.

That is why I defined it before `"${java_opts_array[@]}"`, so that it could be overridden by `$JAVA_OPTS`.

**Comment by oleg-nenashev** [comment]
@jglick is this override behavior standartized across Java versions?

**Comment by oleg-nenashev** [comment]
@carlossg Well, we had fallout in Remoting agent image due to conflicting options. That's why I was asking. If you feel strongly, go for it.

**Pull request merged**
