### PR TITLE
Optionally ignore mark_file check

### PR DESCRIPTION
**Pull request by EslamElHusseiny**
* Optionally ignore mark_file check to upgrade plugins that have been upgraded manually with `-e IGNORE_MARKER_FILE=true`.

### CODE REVIEW

**Comment by cornelf** [comment]
👍

**Comment by batmat** [comment]
Retriggering, for some reason PR build status still in progress.

**Comment by oleg-nenashev** [comment]
Will try to get it over the line after the LTS cutoff

**Comment by timja** [comment]
The script is deprecated for removal and we’re no longer taking changes to it

**Pull request closed without merging**
