### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ziqiangxu**
fix: if the UID of current user is not 1000 would occur permission error

### CODE REVIEW

**Comment by slide** [comment]
I think this would be better as a note with an additional example rather than changing the existing example.

**Comment by oleg-nenashev** [comment]
@ziqiangxu aee you still interested in this pull request?

**Comment by ziqiangxu** [comment]
Is  here anything need to do?

**Comment by timja** [comment]
Closing as comment not addressed after nearly 2 years

**Pull request closed without merging**
