### PR TITLE
#790: allow manually upgraded plugins to be upgraded

### PR DESCRIPTION
**Pull request by lifeofguenter**
Currently it is impossible to automatically upgrade plugins once they have been manually upgraded (see: https://github.com/jenkinsci/docker/issues/790) - this PR allows one to force plugin upgrades even if it has been manually upgraded.

I have not tested this yet though.

### CODE REVIEW

**Comment by lifeofguenter** [comment]
I ran a test-run, the results of the `copy_reference_file.log` file:

```
--- Copying files at Sun Apr  7 09:00:05 UTC 2019
UPGRADED plugins/blueocean-dashboard.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-autofavorite.jpi : Image version (1.2.4) is newer than installed version (1.2.3)
UPGRADED plugins/blueocean-pipeline-api-impl.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-i18n.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-jwt.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-web.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/cloudbees-bitbucket-branch-source.jpi : Image version (2.4.3) is newer than installed version (2.4.2)
UPGRADED plugins/basic-branch-build-strategies.jpi : Image version (1.3.0) is newer than installed version (1.2.0)
UPGRADED plugins/cloudbees-folder.jpi : Image version (6.8) is newer than installed version (6.7)
UPGRADED plugins/variant.jpi : Installed version (1.2) has been manually upgraded from initial version (1.1), forcing upgrade
UPGRADED plugins/blueocean-pipeline-scm-api.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-rest.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/jenkins-design-language.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-pipeline-editor.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/junit.jpi : Installed version (1.27) has been manually upgraded from initial version (1.26.1), forcing upgrade
UPGRADED plugins/script-security.jpi : Installed version (1.56) has been manually upgraded from initial version (1.51), forcing upgrade
UPGRADED plugins/branch-api.jpi : Image version (2.3.0) is newer than installed version (2.2.0)
UPGRADED plugins/blueocean-events.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-core-js.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-commons.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-github-pipeline.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-personalization.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-jira.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
SKIPPED plugins/git.jpi : Image version (3.9.3) is older than installed version (4.0.0-rc)
UPGRADED plugins/blueocean-rest-impl.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/workflow-durable-task-step.jpi : Image version (2.30) is newer than installed version (2.29)
UPGRADED plugins/docker-plugin.jpi : Installed version (1.1.6) has been manually upgraded from initial version (1.1.5), forcing upgrade
SKIPPED plugins/git-client.jpi : Image version (2.7.6) is older than installed version (3.0.0-rc)
UPGRADED plugins/timestamper.jpi : Installed version (1.9) has been manually upgraded from initial version (1.8.10), forcing upgrade
UPGRADED plugins/scm-api.jpi : Image version (2.4.1) is newer than installed version (2.4.0)
UPGRADED plugins/blueocean-git-pipeline.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/docker-commons.jpi : Image version (1.14) is newer than installed version (1.13)
UPGRADED plugins/docker-workflow.jpi : Image version (1.18) is newer than installed version (1.17)
UPGRADED plugins/blueocean-bitbucket-pipeline.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
UPGRADED plugins/blueocean-config.jpi : Installed version (1.14.0) has been manually upgraded from initial version (1.10.2), forcing upgrade
```

notice all the upgraded log entries that end with "forcing upgrade" - those are plugins that would have not been upgraded without the changes.

Update center looks like this:

Screenshot from 2019-04-07 11-07-42

Which is generally good:

1. I am pinning the version for the ec2 plugin via the `plugins.txt` which gets consumed by `install-plugins.sh`
2. I have no idea about pam-auth. It seems like a dependency of another plugin, but I do not find it in the logs of `install-plugins.sh` nor `copy_reference_file.log` - might be a separate issue.

**Comment by carlossg** [comment]
Fixes #790

**Comment by carlossg** [comment]
looks good to me but I think it deserves a test in `tests/install-plugins.bats` `tests/install-plugins/Dockerfile`

**Comment by carlossg** [comment]
Actually this will also downgrade plugins and duplicates what's in #577, let's move the conversation there

**Pull request closed without merging**
