### PR TITLE
End of Life of `tini-shim` at `/bin/tini`

### PR DESCRIPTION
**Pull request by basil**
`tini-shim.sh` contains:

> Please update your scripts to use `/sbin/tini` or simply `tini` going forward. Previous path has been preserved for backwards compatibility, but WILL BE REMOVED in the future. (around Jenkins >= 2.107.2+)

That was _four years_ ago.

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
Thanks! LGTM.

Checks are failing because of the DockerHub APi rate limit in official images (no worris for ci.jenkins.io: all the `jenkins/*` and `jenkinsciinfra/*` are not rate-limited).


Do you mind updateing the title of the pull request? The acronym "EOL" is not easy for non-natives: the changelog would be easier to understand with something like "Removing tini-shim from /bin/tini", what do you think?

**Comment by basil** [comment]
I think [EOL](https://en.wikipedia.org/wiki/End-of-life_product) is a standard term in the tech industry.

**Comment by dduportal** [comment]
> I think [EOL](https://en.wikipedia.org/wiki/End-of-life_product) is a standard term in the tech industry.

The term "End Of Life" is clear. But as a non native English speaker, I've struggled to understand what acronyms means (also true even in my native language).
The context switching associated to "ok have to search the meaning, and translate in mental model based on english level" is an obstacle to many people
It might be an habit for a lot of long-time experts but it is slowing down communication (pretty interested reading - opinionated though- about this topic  https://www.futurity.org/abbreviations-science-communication-1358852-2).

My request is only about "using full words instead of acronym".

**Comment by basil** [comment]
I do not feel like arguing about this.

**Comment by basil** [comment]
No objection at all. You are the maintainer.

**Review by timja — APPROVED** [review]

**Review by dduportal — APPROVED** [review]

**Pull request merged**
