### PR TITLE
Use plugin installation manager 2.7.0

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Use plugin installation manager 2.7.0

See the [2.7.0 changelog](https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.7.0).

### CODE REVIEW

**Comment by MarkEWaite** [comment]
The test failures are also happening on the master branch and are visible on two local computers that I use for development.  The failures were not visible on one of the two local computers until I used `docker rmi` to remove all the bats.*alpine images.

I don't understand why the tests are failing now when they were passing previously.  The last change to the source code in this repository was two weeks ago.  However, the [AdoptOpenJDK base Docker image](https://hub.docker.com/layers/adoptopenjdk/openjdk8/jdk8u282-b08-alpine/images/sha256-c293c71734ffe23e1bf2c22c54528a68850f2dfd94fa3e43c9f5adf1516bc51b?context=explore) was updated recently.  That may be the cause of the issue.

**Comment by kwin** [comment]
Meanwhile we have 2.7.0 (https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.7.0). Would be nice to update to that version (once the underlying docker issues are solved).

**Comment by MarkEWaite** [comment]
Needs update to 2.7.0 (Thanks @kwin!)

**Comment by MarkEWaite** [comment]
I ran the tests on 4 different computers without a failure, but that was after previously having failures on the same computers.  Still no idea why tests are unreliable.

**Review by slide — APPROVED** [review]

**Comment by rbjorklin** [comment]
There were multiple releases in the last few hours, could this be bumped again?
https://github.com/jenkinsci/plugin-installation-manager-tool/releases

**Comment by MarkEWaite** [comment]
@rbjorklin I submitted https://github.com/jenkinsci/docker/pull/1087 to update to 2.8.0, though I suspect we'll need to use dependabot to track those releases since plugin installation manager appears to be delivering a release on each feature commit.

**Pull request merged**
