### PR TITLE
Update Plugin CLI

### PR DESCRIPTION
**Pull request by torstenwalter**
It was already updated in most of the Dockerfiles

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1

**Review by slide — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Comment by torstenwalter** [comment]
Wow: Three approvals!

And a broken build where I do not see how that's related to the changes.

**Comment by MarkEWaite** [comment]
> Wow: Three approvals!
> 
> And a broken build where I do not see how that's related to the changes.

Unfortunately, we've not had time to diagnose the problem that is causing some of the ci.jenkins.io agents to disconnect randomly.  The "Checks" tab in GitHub now includes a "Re-run" button that allows pull requests to be run again.  I clicked that to run the PR checks again.

Screenshot 2020-10-19 105357

**Comment by slide** [comment]
Looks like the build is failing because there is no room left on the agent file system.

**Comment by torstenwalter** [comment]
Do you know if the space problem is fixed by now?
I don't see the re-run button otherwise I would trigger a pipeline myself.

**Pull request merged**
