### PR TITLE
feat: Added Elestio as one-click deploy option

### LINKED ISSUE #1928: Adding Elestio as deployment option
### Describe your use-case which is not covered by existing documentation.

Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Jenkins application as shown [here](https://elest.io/open-source/jenkins). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

- https://elest.io/open-source/jenkins

### Are you interested in contributing to the documentation?

[Deploy on Elestio](https://elest.io/open-source/jenkins)

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
This PR introduces new one-click deployment option - Elestio

Fixes #1928 

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I strongly prefer that links to public cloud hosting services be offered from the [Jenkins download page](https://www.jenkins.io/download/#deploying-jenkins-in-public-cloud) rather than being offered from the docker repository README file.

The [Jenkins download page](https://www.jenkins.io/download/#deploying-jenkins-in-public-cloud) already includes public cloud hosting instructions for:

* [AWS](https://aws.amazon.com/blogs/devops/setting-up-a-ci-cd-pipeline-by-integrating-jenkins-with-aws-codebuild-and-aws-codedeploy/)
* [Azure](https://docs.microsoft.com/en-us/azure/developer/jenkins/)
* [Google Cloud](https://cloud.google.com/architecture/using-jenkins-for-distributed-builds-on-compute-engine)
* [CIVO](https://github.com/civo/kubernetes-marketplace/tree/master/jenkins)
* [Oracle Cloud](https://docs.oracle.com/en/solutions/cicd-pipeline/)
* [Bitnami](https://bitnami.com/stack/jenkins/cloud)

The [improve this page link](https://github.com/jenkins-infra/jenkins.io/edit/master/content/download/index.html.haml) on the downloads page will take you to the file that needs to be extended.

If we add the public cloud hosting providers to the Docker documentation, we should also add them to the helm chart documentation.  I think it is better to place public cloud provider links in the central location rather than spread it into multiple repositories.  We could link from the Docker and Helm chart documentation to that location as a way to increase visibility.

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
See [my earlier comment](https://github.com/jenkinsci/docker/pull/1929#issuecomment-2348680357)

**Comment by MarkEWaite** [comment]
We discussed this in the Platform SIG meeting 24 Sep 2024 and decided this needs to be proposed to the downloads page rather than the container image documentation.

**Comment by kaiwalyakoparkar** [comment]
Thanks for letting me know @MarkEWaite, Can you please share the link for the downloads page? I will make a pr to it :)

**Pull request closed without merging**
