### PR TITLE
reference #207 - Filter out plugins already installed

### PR DESCRIPTION
**Pull request by jimzucker**
Example output:

➜  jenkinsci_docker git:(filterPlugins) ✗ docker exec -t angry_kilby bash  /tmp/plugins.sh /tmp/plugins.txt
  ... skipping already installed:  ant:1.2
  ... skipping already installed:  antisamy-markup-formatter:1.1
  ... skipping already installed:  credentials:1.18
Downloading cucumber-testresult-plugin:0.8.2
  ... skipping already installed:  cvs:2.11
  ... skipping already installed:  external-monitor-job:1.4
Downloading git-client:1.19.0
Downloading git:2.4.0
  ... skipping already installed:  javadoc:1.1
  ... skipping already installed:  junit:1.2-beta-4
  ... skipping already installed:  ldap:1.11
  ... skipping already installed:  mailer:1.11
  ... skipping already installed:  matrix-auth:1.1
  ... skipping already installed:  matrix-project:1.4.1
  ... skipping already installed:  maven-plugin:2.7.1
  ... skipping already installed:  maven-plugin:2.7.1
  ... skipping already installed:  pam-auth:1.1
Downloading scm-api:1.0
  ... skipping already installed:  script-security:1.13
  ... skipping already installed:  ssh-credentials:1.10
  ... skipping already installed:  ssh-slaves:1.9
  ... skipping already installed:  subversion:1.54
  ... skipping already installed:  translation:1.10
  ... skipping already installed:  windows-slaves:1.0
➜  jenkinsci_docker git:(filterPlugins) ✗

### CODE REVIEW

**Comment by gmacario** [comment]
Is there a reason why you deleted `set -e`?

**Comment by Vlatombe** [comment]
I don't see the point. plugins.sh is meant to be executed during docker build, not during docker run.

**Comment by gmacario** [comment]
I believe that leaving `set -e` would detect cases (even during docker buidl) where plugins cannot be downloaded - i.e. for network issues between the build host and the registry.

**Comment by jimzucker** [comment]
My egrep was causing it to exit, do you have an idea how to fix that and put back the -e ?  I see the value to have the build fail(from other comment).



Sent from my iPhone

On Mar 2, 2016, at 00:15, Gianpaolo Macario <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a reason why you deleted set -e?

-

**Comment by jimzucker** [comment]
I fixed the script to put the -e back, that was a good catch.

**Comment by gmacario** [comment]
> do you have an idea how to fix that and put back the -e ?

How about https://github.com/jenkinsci/docker/pull/216 ?

**Comment by carlossg** [comment]
Did you read Vincent's comment? plugins.sh is executed at build time, not runtime so the JENKINS_HOME is not present

**Comment by jimzucker** [comment]
@carlossg I should have caught that, I will review today.

**Comment by jimzucker** [comment]
@carlossg I reviewed and retested, it works OK in my test case, the script does not access $JENKINS_HOME, I think we are OK. Can you clarify the test case I should review?

---> 76da51b9d3a6
Removing intermediate container 516bb2ba7a16
Step 7 : RUN /usr/local/bin/plugins.sh /usr/share/jenkins/ref/plugins.txt
---> Running in ea11274d3389
ls: cannot access /var/jenkins_home/plugins/*: No such file or directory
Downloading cucumber-testresult-plugin:0.8.2
Downloading scm-api:1.0
Downloading git-client:1.19.0
Downloading git:2.4.0
Downloading maven-plugin:2.7.1
---> 713132a3c006
Removing intermediate container ea11274d3389

**Comment by jimzucker** [comment]
@carlossg I see the issue I can't access:
  ls: cannot access /var/jenkins_home/plugins/*: No such file or directory

My original testing was flawed.  I will close this and give it some thought.

**Pull request closed without merging**
