### PR TITLE
Multiple enhancement in `Dockerfile` and `jenkins.sh` (jessie)

### PR DESCRIPTION
**Pull request by frntn**
Improvements:
- [x] Improve code readability in `copy_reference_file` function
- [x] Improve code genericity in `copy_reference_file` function (dynamically extract string subsets)
- [x] Improve log output format : oneliner status + use `copy:` and `skip:` prefixes
- [x] Improve Dockerfile readability
- [x] Various minor Dockerfiles fixes (use group in chmod, protect vars with double quotes,...)

Upgrades:
- [x] Jenkins 2.8
- [x] tini 0.9.0

### CODE REVIEW

**Comment by carlossg** [comment]
Hi @frntn , thanks for the PR, but it is better to have smaller ones that are easier to review/discuss.

Some comments:
jenkins 2.8 -> this image is only for Jenkins LTS. Weekly builds are automatically pushed to jenkinsci/jenkins
is the reordering improving something? is it just a reorganization?

**Comment by frntn** [comment]
Thanks for your comments @carlossg
I have removed Jenkins 2.8 upgrade.

Changes in the `Dockerfile` are mostly : 

- [x] genericity improvement (2065172, ca1eab7), 
- [x] readability / reorganization (8bf4874, 6c9badb, df99edd), 
- [x] reliability / best pratices (f01acf1, 05da69c, 23fefaf,9716b98)

Changes in the `jenkins.sh` is one commit (46c7a00) that includes genericity, readability and log output improvement. I should have split this one I agree !

**Comment by carlossg** [comment]
Unfortunately this fell through the cracks and now has merge conflicts. 
I don't see much value on the Dockerfile reorg but the copy_reference_file changes could be useful, if you'd like to rebase

**Comment by ndeloof** [comment]
please split this into smaller changes so we can review them

**Pull request closed without merging**
