### PR TITLE
provide a way to build multiple arch

### PR DESCRIPTION
**Pull request by Tony-Proum**
Would like to create an official Jenkins container that could be ran on a raspberrypi or other arch. 
I thought that this could be a first step, but don't know how the tag should be manage in the publishing workflow. 

(Not sure: is this the right place to do so ?)

### CODE REVIEW

**Comment by Tony-Proum** [comment]
seems to be an issue with the way Jenkins's docker-workflow-plugin handle the build result https://issues.jenkins-ci.org/browse/JENKINS-44609

**Comment by Tony-Proum** [comment]
@carlossg @ndeloof provided that I'm able to fix the docker-workflow-plugin issue, do you think that we could add this type image to the official jenkins repository ?

**Comment by carlossg** [comment]
I don't think you can build other arch from let's say x86_64. 
Building other architectures would then involve first having the right build machines in the jenkins infra to do the builds

**Comment by Tony-Proum** [comment]
Oh you're right, I'll study this point. (I think that hosting an official image build from my own is not a very good idea)

**Comment by oleg-nenashev** [comment]
https://github.com/jenkinsci/docker/pull/719 probably addresses this ticket

**Pull request closed without merging**
