### PR TITLE
Upgrade to the new LTS baseline: 2.19.1

### PR DESCRIPTION
**Pull request by rtyler**
See also https://jenkins.io/changelog-stable/#v2.19.1

### CODE REVIEW

**Comment by rtyler** [comment]
Some bats tests are failing in Jenkins and I don't know why :frowning_man:

**Comment by jvrplmlmn** [comment]
@carlossg @rtyler seems like the 2.7.4 tag got overwritten with 2.19.1

https://github.com/jenkinsci/docker/commit/332f71bfb37ae810b8d7c06b939d5d5a49a31de5

**Comment by carlossg** [comment]
My bad, will be fixed with https://github.com/docker-library/official-images/pull/2228

**Comment by jvrplmlmn** [comment]
Gracias @carlossg !

**Pull request merged**
