### PR TITLE
Allow JENKINS_UC_LATEST override

### PR DESCRIPTION
**Pull request by cronik**
For users that are using custom update centers (i.e. Artifactory) the query to
get the latest update center does not work as expected. For example the url resolves to `https://artifactory.example.com/artifactory/jenkins-update-center/?version=2.249/latest/...`

By enabling an explicit override to the JENKINS_UC_LATEST this limitation
can be overcome by explicitly setting the dynamic location for the lts version
getting built. For example:

```
ENV JENKINS_UC_LATEST=https://artifactory.example.com/artifactory/jenkins-update-center/dynamic-2.248
```

### CODE REVIEW

**Comment by dnskr** [comment]
I have the same issue.
It would be great to override JENKINS_UC_LATEST by env variable.

**Comment by timja** [comment]
install-plugins.sh is deprecated for removal, we aren't taking any changes to the script

**Comment by alexjfisher** [comment]
@timja Do you know when it might be replaced?  This is an issue for me too and closing the PR that fixes it without an alternative is disappointing.

**Comment by alexjfisher** [comment]
https://github.com/jenkinsci/docker/pull/1073 perhaps?  Seems to have stalled though.

**Comment by timja** [comment]
It's been replaced over a year ago, there's a script to make it more seamless though in that PR

**Pull request closed without merging**
