### PR TITLE
2.46.1

### PR DESCRIPTION
**Pull request by kuborgh-hgiesenow**
Time for an update :-)

### CODE REVIEW

**Comment by jwhitcraft** [comment]
@kuborgh-hgiesenow can you also create one for the alpine branch?

**Comment by carlossg** [comment]
@jwhitcraft no need to create a PR for alpine, we can just merge from master

**Comment by gmacario** [comment]
Hello @carlossg,

Is there a reason why 2.46.1 is not yet available on https://hub.docker.com/r/library/jenkins/tags/ even thou gh this PR was merged 19 hours ago?

**Comment by carlossg** [comment]
this is done by docker team, otherwise use `jenkinsci/jenkins`

**Comment by gmacario** [comment]
Thanks for the explanation!
I just discovered the open PR https://github.com/docker-library/official-images/pull/2810

**Pull request merged**
