### PR TITLE
Use java 11 in usage instructions

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
No objections. It could probably help us to get some feedback

**Comment by timja** [comment]
> No objections. It could probably help us to get some feedback

documentation everywhere else has been updated (website, helm charts), I don't see why we wouldn't do this

**Review by dduportal — APPROVED** [review]
👍 I don't see any reason to hold on JDK8 when using Docker, unless edge case.
As the JDK8 image still exists, there is no reason to not recommend JDK11 given the other documentation changes

**Comment by timja** [comment]
@MarkEWaite

**Review by MarkEWaite — APPROVED** [review]

**Comment by timja** [comment]
🚢 ?

**Pull request merged**
