### PR TITLE
Experimental Publishing: Explicitly pass --config/--docker-cfg

### PR DESCRIPTION
**Pull request by slide**
This is an attempt to get the correct permissions used for push operations (both docker and manifest-tool invocations) by specifying their respective options to tell them where the docker config.json is located.

### CODE REVIEW

**Comment by slide** [comment]
Close and reopen for a build

**Comment by oleg-nenashev** [comment]
Looks like you missed the reopen part :)
I am really thinking about adding CommentOps functionality to the Jenkins plugins

**Comment by slide** [comment]
Thank, I did miss that...kids needed stuff :-)

**Comment by slide** [comment]
Again...need #860 merged :-)

**Comment by slide** [comment]
Hopefully last close/reopen

**Pull request merged**
