### PR TITLE
cleanup: remove deprecated `install-plugin.sh` script from Linux jdk11 images

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR removes the `install-plugin.sh` script and its addition in the Linux jdk11 images.

From https://github.com/jenkinsci/docker/pull/1857:
> - Deprecated since September 2020
> - Does only echo a warning since https://github.com/jenkinsci/docker/pull/1408 almost two years ago: https://github.com/jenkinsci/docker/blob/bed10d624086e931cf1d053d62174a2355cfd15c/install-plugins.sh
> - I think it's time for it to go, it shouldn't functionally change anything for the end users anyway.

Extracted here if it needs to be merged separately.

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by dduportal — APPROVED** [review]
Good idea! LGTM.

On the "sides", I proposeto  change the PR title to `deprecated` instead of `useless` (less negative connotation) and add the "breaking" label so that the generated changelog would make it a "breaking change" to ensure anyone still using it could immediately see this change starting for the next weekly (and on the next LTS)

**Comment by lemeurherve** [comment]
PR renamed and label added, even if "using it" would be a big word for a script only displaying a warning ^^

**Comment by MarkEWaite** [comment]
> On the "sides", I propose to change the PR title to `deprecated` instead of `useless` (less negative connotation) and add the "breaking" label so that the generated changelog would make it a "breaking change" to ensure anyone still using it could immediately see this change starting for the next weekly (and on the next LTS)

I changed the description to use "deprecated" instead of "useless".

I'm less confident calling this a breaking change.  Users that have called the install-plugins.sh script from within a Dockerfile have failed the build of that Dockerfile since its change in 9b54caaf .  I think that the user perception of the removal is no different.  If they called it before removal, the Dockerfile build failed due to `exit 1`.  If they call it after removal, the Dockerfile build will fail because the script does not exist.

I don't object to this removal, but I'm also fine if this removal waits until the JDK 11 container images are removed with the end of life of Java 11 in October 2024.

**Review by MarkEWaite — APPROVED** [review]

**Comment by lemeurherve** [comment]
> I don't object to this removal, but I'm also fine if this removal waits until the JDK 11 container images are removed with the end of life of Java 11 in October 2024.

If it's OK for you I'd like to merge this PR so I can update my other PR #1857 which needs/implies this change.

**Pull request merged**
