### PR TITLE
CentOS - Use Adoptium JDK

### PR DESCRIPTION
**Pull request by slide**
This updates the CentOS images to use Adoptium rather than the JDK from the normal CentOS repos.

### CODE REVIEW

**Comment by slide** [comment]
Taken from installation steps here: https://adoptopenjdk.net/installation.html#linux-pkg

**Review by olblak — APPROVED** [review]

**Review by oleg-nenashev — APPROVED** [review]
The version is not pinned, but it looks good overall.
Thanks @slide !

**Review by MarkEWaite — APPROVED** [review]
I built the image using the Jenkins 2.276 war file and confirmed that it runs as expected.  I checked the operating system and the JDK that is being used.  Looks good to me.

**Comment by slide** [comment]
Do we want to point the jdk to a specific version? I can look into it.

**Comment by MarkEWaite** [comment]
> Do we want to point the jdk to a specific version? I can look into it.

I'd like that because it makes it explicit that this build is packaging a specific JDK version.

**Comment by slide** [comment]
> > Do we want to point the jdk to a specific version? I can look into it.
> 
> I'd like that because it makes it explicit that this build is packaging a specific JDK version.

Version pinned now to latest at the time of the PR

**Pull request merged**
