### PR TITLE
Fix #331 backport  JENKINS_UC_DOWNLOAD feature in install-plugins.sh

### LINKED ISSUE #331: Backport JENKINS_UC_DOWNLOAD feature in install-plugins.sh
Hi there,

I noticed one week ago that plugins.sh is now deprecated and replaced by install-plugins.sh.
I've seen tons of benefits from the new version but i think we miss the JENKINS_UC_DOWNLOAD.

As far as i know JENKINS_UC_DOWNLOAD variable was originally used in plugins.sh to allow users to use a different mirrors (either cause current one is down OR because you have a paranoid whitelist proxy).

The new version (install-plugins.sh) use JENKINS_UC variable which doesn't contains the full path and expect to have a download folder which is not the case in all mirrors. 
Exemple: 
* http://jenkins.mirror.isppower.de/
* http://ftp.halifax.rwth-aachen.de/jenkins/
* http://mirrors.clinkerhq.com/jenkins/

Is there any particular reason for not integrating it ? if not a pull request is coming :).

Cheers.

### PR DESCRIPTION
**Pull request by jeanlouisboudart**
All the details are in the #331 ticket.

### CODE REVIEW

**Comment by jeanlouisboudart** [comment]
Thx @carlossg :)

**Comment by netrounds-fredrik** [comment]
`install-plugins.sh` is now broken :disappointed::
```
/usr/local/bin/install-plugins.sh: line 65: JENKINS_UC_DOWNLOAD: unbound variable
```

You can not check for undefined variables using `[ -z "$xxx" ]` when the `-u` flag is set. See http://stackoverflow.com/questions/11362250/in-bash-how-do-i-test-if-a-variable-is-defined-in-u-mode

**Comment by jeanlouisboudart** [comment]
@netrounds-fredrik good catch i'll fix that

**Comment by jeanlouisboudart** [comment]
I've just made a new PR #334 to handle it as i'm not able to reopen this one.
I made some test with and without env variable, everything seems ok.

@netrounds-fredrik Could you please make sure it works on your side ? Thx

**Pull request merged**
