### PR TITLE
Fix test issue

### PR DESCRIPTION
**Pull request by slide**
Switch to using junit as the plugin for tests instead of the maven
plugin

### CODE REVIEW

**Comment by slide** [comment]
Does anyone have any ideas on why the test is current failing? From looking at the diff, it should work similarly to how the usage of the maven plugin did, but it fails. I haven't had time to dig in yet.

**Comment by timja** [comment]
Hmm, error is:
```
[2019-12-09T15:40:58.532Z] not ok 13 do not upgrade if plugin has been manually updated
[2019-12-09T15:40:58.532Z] # (from function `assert_line' in file tests/test_helper/bats-assert/src/assert.bash, line 508,

[2019-12-09T15:40:58.532Z] #  in test file tests/install-plugins.bats, line 184)

[2019-12-09T15:40:58.532Z] #   `assert_line 'Plugin-Version: 1.8'' failed
[2019-12-09T15:40:58.532Z] #   Implementation-Version: 1.28
```

Expected,
junit = 1.8
actual,
junit = 1.28

**Comment by slide** [comment]
I had more opportunity to look into this today and it seems like the rm is not working, the directory used for work is still there, so the wrong versions are therr

**Comment by slide** [comment]
Oddly enough, if I add an `ls` as part of the `clean work directory` test, things are working. Maybe there is a file system sync issue or something from the container?

**Comment by slide** [comment]
@oleg-nenashev @MarkEWaite @markyjackson-taulia I'd really like some feedback on this. I don't like the addition of the `ls`, but without it it looks like the directory is not actually being removed for some reason.

**Comment by oleg-nenashev** [comment]
Sorry, missed the pings

**Pull request merged**
