### PR TITLE
Add multi-arch build

### PR DESCRIPTION
**Pull request by timja**
Requires builders to be setup

I followed this medium post:
```
docker buildx create --name remote --use

docker buildx create --name remote \
  --append ssh://jenkins-agent-ppc64le

docker buildx create --name remote \
  --append ssh://jenkins-agent-s390x

# I'm running on arm so didn't actually do this, but for completeness
docker buildx create --name remote \
  --append ssh://jenkins-agent-arm64
```

```ssh-config
Host jenkins-agent-ppc64le
HostName <actualname>
  IdentityFile ~/.ssh/ppc64le
  User jenkins

Host jenkins-agent-s390x
  HostName <actualname>
  IdentityFile ~/.ssh/s390x
  User jenkins

Host jenkins-agent-arm64
  HostName <actualname>
  IdentityFile ~/.ssh/arm64
  User jenkins
```

```
export DOCKERHUB_ORGANISATION=timja # your dockerhub username
./.ci/publish.sh --variant jdk11 --start-after 2.298
```

Result:
https://hub.docker.com/layers/timja/jenkins/2.299-jdk11/images/sha256-cd506b06e00ad8c8f2f931177c70fee4a41d9d1c12f77f46becf632326accb23?context=explore

I _assume_ we can re-use the existing s390x and ppc64le agents we have, and I guess create a static ARM agent?

How would the jenkins agent running here be able to connect to the agent? just set it up on trusted ci and don't do multi arch on build ?

Alternatively we could go the approach of @james-crowley of running the build on an agent of each, publishing the manifests for all and then creating an image from each, at least in the current state of https://github.com/jenkinsci/docker/pull/1034 it seems to publish an image for each architecture from than publishing / assembling manifests and creating a proper multi arch image, publishing manifests is documented as an advanced topic and seems more complex than using `docker buildx build --platform`

Looking for info on how to get this going though, I'm running on ARM and the lack of docker image is a bit of a pain, I can build one locally if I absolutely need to but I tend to avoid it and just skip docker these days.

cc @olblak @slide @MarkEWaite @dduportal

### CODE REVIEW

**Comment by dduportal** [comment]
Some thoughts:

- Intuitively, the solution of "one build on a specialized Jenkins agent" seems the solution, which means pushing the work of @james-crowley to have one pipeline parallel branch per kind of platform.
  - pros: simpler to handle, less resource constraint per machine. Con: requires better build node convention
  - The "dynamic workers" requires to have credentials on the agents where the `docker CLI` is used, which makes it uneasy to run on ci.jenkins.io, not mentioning the risk of having the SSH private key available on the agent filesystem (and double configuration to manage in parallel: one on the controller, the other on agents). The advantage of this one though is that building images does not require to run on a VM with a local Docker Engine. It can even use kubernetes workers as backend for buildx.

- On the asciidoctor official image, we've pushed the use of a "docker bake file": https://github.com/asciidoctor/docker-asciidoctor/blob/main/docker-bake.hcl to define all possible images in the repository, with the possibility to create groups (ref. https://docs.docker.com/engine/reference/commandline/buildx_bake/ ).
  - Never tried using it with multi arch, but I was expecting that the manifest would be updated by the `push` step of buildx on the remote registry. That would be worth it to try
  - Pros of the bake file: parallelisaztion of builds, and the manifest list of images would not be a Makefile/shell or worse a Jenkinsfile.

WDYT we get started with the following:
- Define docker-bake.hcl file with the list of images to ensure a centralized list.
  - Define groups such as `all`, `x64`, `arm64`, `windows`, `s390x`, `linux`, etc.
- Update the pipeline to build (build + tests) in parallel on `Linux x64`, `Linux arm`, `Windows x64` and `Linux s390x`
- Update the Makefile to (for the build step)to execute the docker buildx bake command with the target group (e.g. one of the 4 defined earlier as branch)

=> It would allow to get started quickly to "land" the ARM image without changing too much the ci, and buildx is quite versatile so changing to workers would be a breeze

**Comment by timja** [comment]
Thanks for the feedback @dduportal, that looks interesting, I haven't seen `docker buildx bake` before, looking at the asciidoctor repo I can see it invoked like so:
https://github.com/asciidoctor/docker-asciidoctor/blob/main/Makefile#L17

>  not mentioning the risk of having the SSH private key available on the agent filesystem

I'm not sure if we would need to make it available outside of the workspace dir, would need to see how flexible the docker `ssh://` url is.

**Comment by timja** [comment]
I'm not 100% sure I understand what you mean @dduportal 

> Intuitively, the solution of "one build on a specialized Jenkins agent" seems the solution, which means pushing the work of @james-crowley to have one pipeline parallel branch per kind of platform.

by pipeline do you mean Jenkins or `docker buildx` build?

As I understand it we just need one Jenkins agent with the docker CLI installed.

That will then build on amd64

and then we have SSH credentials setup so that machine can connect to:

* arm64 (needs creating)
* s390x (exists)
* ppc64le (exists)

We can switch to `docker buildx bake` in order to build all images in parallel?

FTR I did try QEMU on our Jenkins agents but it failed with some files descriptor issue, I found a reference to it somewhere that the qeumu update in January must've broken it. I didn't want to spend too much time on it as I wasn't sure if we wanted to risk qemu updates breaking our builds.

**Comment by timja** [comment]
Work progressing in https://github.com/jenkinsci/docker/issues/1139

**Pull request closed without merging**
