### PR TITLE
Fix jenkins-plugin-cli JAVA_OPTS handling

### PR DESCRIPTION
**Pull request by cronik**
The jenkins-plugin-cli.sh helper script does not evaluate correctly when there
are JAVA_OPTS set. JAVA_OPTS needs to be double quoted to prevent word
splitting and globbing. Take the example where JAVA_OPTS sets a proxy and uses
`*`:

```
❯ JAVA_OPTS="-Dhttp.nonProxyHosts=127.0.*,localhost" ./jenkins-plugin-cli.sh --plugins foo
+ exec /bin/bash -c 'java -Dhttp.nonProxyHosts=127.0.*,localhost -jar /opt/jenkins-plugin-manager.jar --plugins foo'
```
The proxy option is not properly quoted when interpreted by the bash command.

By using eval we can resolve the variables and maintain proper word splitting
and globbing behavior.

```
❯ JAVA_OPTS="-Dhttp.nonProxyHosts=127.0.*,localhost" ./jenkins-plugin-cli.sh --plugins foo
+ eval exec java '-Dhttp.nonProxyHosts=127.0.*,localhost' -jar /opt/jenkins-plugin-manager.jar '--plugins foo'
++ exec java '-Dhttp.nonProxyHosts=127.0.*,localhost' -jar /opt/jenkins-plugin-manager.jar --plugins foo
```

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timja** [comment]
@dduportal I think you're more knowledgeable in this area than me, would you be able to take a look?

**Comment by cronik** [comment]
Forgot to include the actual error I noticed with the current script:

```
/bin/bash: line 1: 127.*: command not found
/bin/bash: line 1: *.cluster.local: command not found
```

These values are in the `http.nonProxyHosts` option we pass to the container via `JAVA_OPTS`.

**Comment by cronik** [comment]
This may need some more work :( My test input wasn't actuate so I didn't catch the actual error:

```
❯ JAVA_OPTS="-Dhttp.nonProxyHosts=127.*|10.*" ./jenkins-plugin-cli.sh --plugins foo                                                                                                                                      
+ eval exec java '-Dhttp.nonProxyHosts=127.*|10.*' -jar /opt/jenkins-plugin-manager.jar '--plugins foo'
++ exec java '-Dhttp.nonProxyHosts=127.*'
++ '10.*' -jar /opt/jenkins-plugin-manager.jar --plugins foo
./jenkins-plugin-cli.sh: line 3: 10.*: command not found
```

**Comment by timja** [comment]
Try:

```
 JAVA_OPTS="-Dhttp.nonProxyHosts='127.*|10.*'"
```

or
```
 JAVA_OPTS="-Dhttp.nonProxyHosts=\"127.*|10.*\""
```

or
```
 JAVA_OPTS='-Dhttp.nonProxyHosts="127.*|10.*"'
```

**Comment by cronik** [comment]
Updated the PR to borrow code from the main jenkins.sh script that reads JAVA_OPTS into an array to avoid the need for
eval. This now works correctly with and with JAVA_OPTS defined and handles the case where JAVA_OPTS contains `|`.

```
❯ JAVA_OPTS="-Dhttp.nonProxyHosts=127.*|10.*" ./jenkins-plugin-cli.sh --plugins foo                                                                                                                                     
+ exec java '-Dhttp.nonProxyHosts=127.*|10.*' -jar /opt/jenkins-plugin-manager.jar --plugins foo

❯ ./jenkins-plugin-cli.sh --plugins foo                                                                                                                                                                                 
+ exec java -jar /opt/jenkins-plugin-manager.jar --plugins foo
```

**Review by timja — APPROVED** [review]
Compared it to the other script and looks good

**Review by dduportal — COMMENTED** [review]
(I'm late to the party, but thanks a lot for this change. Make sense!)

**Pull request merged**
