### PR TITLE
Multiarch updates

### PR DESCRIPTION
**Pull request by slide**
Some of the openjdk images have changed such that they don't work without using the `stretch` version instead of the base image. These changes correct that as well as introduce retries for manifest operations. The time it takes to do certain tasks causes the token to "timeout" and not work after a period of time, if the script receives a 401 (Unauthorized) (really a non 404 or 200) response, it will request a new login token to retrieve manifests and retry the `curl` invocation with the new TOKEN value.

Added the capability to specify a `-a` parameter to only build a single arch. This is mainly for debug, testing purposes.

### CODE REVIEW

**Comment by slide** [comment]
Close/reopen for a build

**Comment by slide** [comment]
One more time...

**Comment by jmreicha** [comment]
I think a similar issue came up with the `publish` script that wasn't ported over to the `publish-expiremental` script?

I can't even remember now exactly what's different between the two but I was planning on getting them merged together if we ever got this part done.

**Comment by slide** [comment]
@jmreicha I looked at publish.sh and didn't see anything related to the token stuff (is that what you were referring to?). I think the publish-experimental.sh is more likely to encounter the issue because there are many more builds that take place because of the different architectures and they are running under qemu which will be slow in general.

**Comment by slide** [comment]
@oleg-nenashev any issues with this?

**Pull request merged**
