### PR TITLE
Install plugins even when they already exist in a different version

### PR DESCRIPTION
**Pull request by carlossg**
@reviewbybees

### CODE REVIEW

**Comment by Vlatombe** [comment]
🐝

**Comment by netrounds-fredrik** [comment]
Note that this will always download the plugin if a version is not specified or specified as "latest". Is it the expected behavior?

**Comment by carlossg** [comment]
So you are saying that `install-plugins.sh maven` will always install the latest even if it is included in the war?

**Comment by netrounds-fredrik** [comment]
Well, I haven't tested, but let's run the code through our head:

1. The argument to the command is "maven"
2. `download` will be called with an empty string as version argument.
3. The empty version string will be replaced by "latest".
4. `doDownload` will be called with version "latest".
5. `grep "^Plugin-Version: latest$"` will probably not match the version number of an already installed maven plugin.
6. The latest version of the maven plugin is downloaded.

You have a similar "issue" in `resolveDependencies` where a dependency that does not specify a version will always cause the latest version to be downloaded, even if there is a version already installed.

You could argue that it's noting wrong in doing like this, but I think that the behavior should be explicitly described in that case.

**Comment by carlossg** [comment]
If version is not set there is no way to know if there is a new version without downloading, so I think it is the right approach to always download the plugin

dependencies always specify a version

**Comment by jglick** [comment]
FTR I still maintain that it is a terrible idea to allow plugins to be listed without versions, as it makes for nondeterministic image builds. Adding a tool suggesting a diff to your `plugins.txt` based on available updates is great, but you should have to decide to apply that diff and commit it.

**Pull request merged**
