### PR TITLE
Update actions/checkout to v3

### PR DESCRIPTION
**Pull request by Sushrut1101**
for hacktoberfest 2022 :)

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
I reviewed the changelog for v3 and it looks reasonable to me.  Thanks!

**Comment by Sushrut1101** [comment]
> I reviewed the changelog for v3 and it looks reasonable to me. Thanks!

You're welcome!

> I reviewed the changelog for v3 and it looks reasonable to me. Thanks!

You're welcome!
Can you add the "hacktoberfest-accepted" label to it please?

**Comment by MarkEWaite** [comment]
It should not need the `hacktoberfest-accepted` label.  The repository already has the `hacktoberfest` topic.  That makes all merged pull requests automatically accepted by Hacktoberfest.  Could you check your [Hacktoberfest dashboard](https://hacktoberfest.com/profile/) to confirm that?

I checked that https://github.com/jenkinsci/emailext-template-plugin/pull/73 is visible on my Hacktobefest dashboard without the `hacktoberfest-accepted` label.

**Comment by Sushrut1101** [comment]
> It should not need the `hacktoberfest-accepted` label. The repository already has the `hacktoberfest` topic. That makes all merged pull requests automatically accepted by Hacktoberfest. Could you check your [Hacktoberfest dashboard](https://hacktoberfest.com/profile/) to confirm that?
> 
> I checked that [jenkinsci/emailext-template-plugin#73](https://github.com/jenkinsci/emailext-template-plugin/pull/73) is visible on my Hacktobefest dashboard without the `hacktoberfest-accepted` label.

Yeah, I can see that now!
Thanks!

**Pull request merged**
