### PR TITLE
INFRA-3016 Pre-create volume for permissions propogation update

### PR DESCRIPTION
**Pull request by timja**
Co-authored-by: Damien Duportal <damien.duportal@gmail.com>

Alternative to https://github.com/jenkinsci/docker/pull/1124

User ID changed on infra from 1000 to 1001. Part of moving to no sudo for jenkins agent user. User 1000 is already defined in AMI so we can't use that user.

### CODE REVIEW

**Comment by dduportal** [comment]
Ref. https://issues.jenkins.io/browse/INFRA-3016

**Comment by saper** [comment]
Sadly it does not seem to fix my issue (local build on fedora 33, with user 1000)... need to check

**Comment by timja** [comment]
> Sadly it does not seem to fix my issue (local build on fedora 33, with user 1000)... need to check

Is your build failing on this test or others?

My mac doesn't pass all the tests.

**Comment by saper** [comment]
Others:

```
DIRECTORY="8/centos/centos8/hotspot" bats/bin/bats tests | tee target/results-centos.tap
1..45
ok 1 [8-centos-centos8-hotspot] build image
ok 2 [8-centos-centos8-hotspot] versionLT
ok 3 [8-centos-centos8-hotspot] permissions are propagated from override file
ok 4 [8-centos-centos8-hotspot] build image
ok 5 [8-centos-centos8-hotspot] plugins are installed with install-plugins.sh
ok 6 [8-centos-centos8-hotspot] plugins are installed with install-plugins.sh with non-default REF
ok 7 [8-centos-centos8-hotspot] plugins are installed with install-plugins.sh from a plugins file
ok 8 [8-centos-centos8-hotspot] plugins are installed with install-plugins.sh even when already exist
ok 9 [8-centos-centos8-hotspot] clean work directory
not ok 10 [8-centos-centos8-hotspot] plugins are getting upgraded but not downgraded
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/install-plugins.bats, line 130)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
# --
# 
ok 11 [8-centos-centos8-hotspot] clean work directory
not ok 12 [8-centos-centos8-hotspot] do not upgrade if plugin has been manually updated
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/install-plugins.bats, line 163)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
# --
# 
ok 13 [8-centos-centos8-hotspot] clean work directory
not ok 14 [8-centos-centos8-hotspot] upgrade plugin even if it has been manually updated when PLUGINS_FORCE_UPGRADE=true
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/install-plugins.bats, line 195)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
# --
# 
ok 15 [8-centos-centos8-hotspot] clean work directory
ok 16 [8-centos-centos8-hotspot] plugins are installed with install-plugins.sh and no war
ok 17 [8-centos-centos8-hotspot] Use a custom jenkins.war
ok 18 [8-centos-centos8-hotspot] clean work directory
ok 19 [8-centos-centos8-hotspot] build image
ok 20 [8-centos-centos8-hotspot] plugins are installed with jenkins-plugin-cli
ok 21 [8-centos-centos8-hotspot] plugins are installed with jenkins-plugin-cli with non-default REF
ok 22 [8-centos-centos8-hotspot] plugins are installed with jenkins-plugin-cli from a plugins file
ok 23 [8-centos-centos8-hotspot] plugins are installed with jenkins-plugin-cli even when already exist
ok 24 [8-centos-centos8-hotspot] clean work directory
not ok 25 [8-centos-centos8-hotspot] plugins are getting upgraded but not downgraded
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/plugins-cli.bats, line 128)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
# --
# 
ok 26 [8-centos-centos8-hotspot] clean work directory
not ok 27 [8-centos-centos8-hotspot] do not upgrade if plugin has been manually updated
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/plugins-cli.bats, line 161)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
# --
# 
ok 28 [8-centos-centos8-hotspot] clean work directory
not ok 29 [8-centos-centos8-hotspot] upgrade plugin even if it has been manually updated when PLUGINS_FORCE_UPGRADE=true
# (from function `assert_success' in file tests/test_helper/bats-assert/src/assert.bash, line 114,
#  in test file tests/plugins-cli.bats, line 193)
#   `assert_success' failed
# 
# -- command failed --
# status : 1
# output (2 lines):
#   Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
#   touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
# --
# 
ok 30 [8-centos-centos8-hotspot] clean work directory
ok 31 [8-centos-centos8-hotspot] plugins are installed with jenkins-plugin-cli and no war
ok 32 [8-centos-centos8-hotspot] Use a custom jenkins.war
ok 33 [8-centos-centos8-hotspot] clean work directory
ok 34 [8-centos-centos8-hotspot] JAVA_OPTS environment variable is used with jenkins-plugin-cli
ok 35 [8-centos-centos8-hotspot] clean work directory
ok 36 [8-centos-centos8-hotspot] build image
ok 37 [8-centos-centos8-hotspot] clean test containers
ok 38 [8-centos-centos8-hotspot] test multiple JENKINS_OPTS
ok 39 [8-centos-centos8-hotspot] test jenkins arguments
ok 40 [8-centos-centos8-hotspot] timezones are handled correctly
ok 41 [8-centos-centos8-hotspot] create test container
ok 42 [8-centos-centos8-hotspot] test container is running
not ok 43 [8-centos-centos8-hotspot] Jenkins is initialized
# (from function `retry' in file tests/test_helpers.bash, line 40,
#  in test file tests/runtime.bats, line 60)
#   `retry 30 5 test_url /api/json' failed
# Command "test_url /api/json" failed 30 times. Status: 1. Output: URL http://localhost:32773/api/json failed
# output: 
not ok 44 [8-centos-centos8-hotspot] JAVA_OPTS are set
# (from function `assert' in file tests/test_helpers.bash, line 19,
#  in test file tests/runtime.bats, line 65)
#   `assert 'default-src &#039;self&#039;; script-src &#039;self&#039; &#039;unsafe-inline&#039; &#039;unsafe-eval&#039;; style-src &#039;self&#039; &#039;unsafe-inline&#039;;' \' failed
# curl: (22) The requested URL returned error: 401
# expected: "default-src &#039;self&#039;; script-src &#039;self&#039; &#039;unsafe-inline&#039; &#039;unsafe-eval&#039;; style-src &#039;self&#039; &#039;unsafe-inline&#039;;"
# actual:   ""
ok 45 [8-centos-centos8-hotspot] clean test containers
docker run --rm -v "/home/saper/space/docker":/usr/src/app \
				-w /usr/src/app node:12-alpine \
				sh -c "npm install tap-xunit -g && cat target/results-centos.tap | tap-xunit --package='jenkinsci.docker.centos' > target/junit-results-centos.xml"
Error: EACCES: permission denied, scandir '/usr/src/app'
sh: can't create target/junit-results-centos.xml: Permission deniedcat: can't open 'target/results-centos.tap': Permission denied

sh: tap-xunit: not found
```

I'll try userns mode.

I have user 1000 and group 1001 there

**Comment by timja** [comment]
Probably best to take this elsewhere then, this PR is to fix CI issues, @dduportal has a separate PR to try fix some issues https://github.com/jenkinsci/docker/pull/1126

**Review by MarkEWaite — APPROVED** [review]
Passes when I run tests on my local Ubuntu computer.

**Pull request merged**
