### PR TITLE
chore: add support for the artifact ignore list

### PR DESCRIPTION
**Pull request by lemeurherve**
This PR adds support for the artifact ignore list defined at https://github.com/jenkins-infra/update-center2/blob/master/resources/artifact-ignores.properties to prevent publishing images of releases we choose to not publish.

Ref:
- https://github.com/jenkinsci/docker/issues/946

### Testing done

Local tests.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by timja — APPROVED** [review]
looks ok, we haven't done this in years but 🤷

**Comment by lemeurherve** [comment]
@daniel-beck do you think it still worth introducing this?

**Comment by MarkEWaite** [comment]
I agree with @daniel-beck .  I don't think we need this addition because we only build when a new annotated tag is detected.

**Comment by lemeurherve** [comment]
Thanks for your comments!

Closing this pull request and #946.

**Pull request closed without merging**
