### PR TITLE
2.32.3

### PR DESCRIPTION
**Pull request by jonahermansen**
Upgrade to latest LTS version

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Is there still something that needs to be done to build the resulting image for this?
Docker hub doesn't show a 2.32.3 tag yet.

**Comment by alokjoshi89** [comment]
Very much waiting for the docker image for 2.32.3

**Comment by jonahermansen** [comment]
2.32.3 got pushed to Docker Hub yesterday

**Comment by simonvanderveldt** [comment]
@jonahermansen awesome, thanks!

**Pull request merged**
