### PR TITLE
Update README and allow changing the mirror with and environment variable.

### PR DESCRIPTION
**Pull request by apottere**
Note that I removed trailing whitespace from some parts of the script - this makes the diff have lines marked as changed that look identical.

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks @apottere. Why do we need another `JENKINS_MIRROR` var instead of setting `JENKINS_UC` pointing to the mirror? is there any mirror not following the `/downloads` path?

**Comment by apottere** [comment]
@carlossg It's JENKINS_UC that's the oddball.  Since it's not a strict mirror (it has other info as well on the root), the "mirror" location is `/download`.  Therefore the default mirror is $JENKINS_UC/download.  Changing JENKINS_UC doesn't work for using a different mirror, because the script would add /download and nothing would resolve.

**Comment by apottere** [comment]
For comparison:

https://updates.jenkins-ci.org/download/
http://mirror.xmission.com/jenkins/

Notice the "plugins" and "war" directories are present and should be identical.

**Comment by carlossg** [comment]
@apottere can you review #314 and see if that works?

**Pull request closed without merging**
