### PR TITLE
Verify git-lfs download

### PR DESCRIPTION
**Pull request by saper**
Follow-up to #1143 - just for some Docker images for review  - as suggested in https://github.com/jenkinsci/docker/pull/1143#issuecomment-876630354

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dduportal** [comment]
Thanks a lot @saper , this method sounds good! Do you mind generalizing it to all images?

**Comment by MarkEWaite** [comment]
I like the technique very much but have been unable to understand why the build process fails both on ci.jenkins.io and for me locally.  The ci.jenkins.io failure example is at https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1144/4/pipeline#step-43-log-1514  .  When running a first build, I see the same failure.

**Comment by dduportal** [comment]
@MarkEWaite 
- Build #4 received a termination signal during the linux build steps. You can diagnose it by looking at the build output for the "CANCELED" occurences (such as https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1144/4/pipeline/40#step-43-log-1444). => It's an OOM or CPU overusage, because all the builds are done at the same time. If the agent are reused from previous builds, their behavior is erratic under this kind of pressure. #1130 aims to solve this erratic behavior.
- Builds #5 and #6 were manually stopped, I'm not sure to understand why?
- [Build #7](https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1144/7/pipeline) successfully passed the build step => the PR is good for me on the method, only have to make it the same for all linux machines

**Comment by dduportal** [comment]
Thanks @saper ! It looks like that `gpg` is missing on the alpine JDK8 as per: https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1144/16/pipeline#step-198-log-121

**Comment by saper** [comment]
> Thanks @saper ! It looks like that `gpg` is missing on the alpine JDK8 as per: https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/detail/PR-1144/16/pipeline#step-198-log-121

Yeah, love that duplication in Dockerfiles... fixed.

**Comment by dduportal** [comment]
Thanks ! I’m not aware of a builtin situation (i would argue that we don’t need multiple distribution for this image), but do you think it could be useful to factorize this logic to shell script (and then copy + run in the dockerfile) to centralize the version management ?

**Review by timja — APPROVED** [review]

**Pull request merged**
