### PR TITLE
provide $JENKINS_HOME as ARG to make it customizable

### PR DESCRIPTION
**Pull request by lanwen**
Replaces #482

### CODE REVIEW

**Comment by batmat** [comment]
There are still a few occurrences for `/var/jenkins_home`.

I think the only place where it should be updated/adjusted is the README, though. The others seem fine (the tests should probably be adapted too, but as is I think they'll keep working by using /var/jenkins_home as long as we keep the default to this value)

**Comment by lanwen** [comment]
Hey, whats up? :) What stops you from merge?

**Comment by lanwen** [comment]
ping?

**Comment by carlossg** [comment]
sorry!

**Pull request merged**
