### PR TITLE
Reference #206 - Added example to get a list of plugins in the required format

### PR DESCRIPTION
**Pull request by jimzucker**
Updated the README.md to give instructions to extract a list of plugins from an existing server to create the list in the format required to create a plugin.txt file.

### CODE REVIEW

**Comment by carlossg** [comment]
if instead of using `curl -L` you use `curl -sSL` it would probably be more clear without the header rows, wouldn't it?

**Comment by jimzucker** [comment]
@calossg - great idea, updated and tested.

**Comment by carlossg** [comment]
LGTM can you squash and I'll merge?

**Comment by jimzucker** [comment]
@carlossg - I squashed it can you please merge.

**Comment by jimzucker** [comment]
@carlossg do you need me to make further changes to move this forward?

**Pull request merged**
