### PR TITLE
add version in resolveDependencies function, fixes download latest ve…

### PR DESCRIPTION
**Pull request by fly2wind**
we use script to install the workflow-job plugin
```
install-plugin.sh workflow-job
```
workflow-job depends on workflow-api:2.15,mailer:2.10,workflow-support:2.14

we hope downloaded mailer:2.10

but,
```
Downloading plugin: mailer from https://updates.jenkins-ci.org/download/plugins/mailer/latest/mailer.hpi
```

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Hard to say whether it is a bug or feature. "Latest if not defined explicitly" is how the entire Docker infrastructure works. And the update maybreak some instances by downgrading the plugins.

Needs feedback from @carlossg  and @ndeloof

**Comment by oleg-nenashev** [comment]
Also @jenkinsci/code-reviewers since the same behavior happens in update centers

**Comment by daniel-beck** [comment]
While this makes things more reproducible, it is inconsistent with Jenkins update center (UI) behavior.

Additionally it will just invite people to keep running long outdated versions of plugins (and still ask questions on mailing lists and file bugs, wasting everyone's time).

No strong opinion either way, but this does not seem like a positive change.

**Comment by ndeloof** [comment]
plugin developers indeed use to rely on very old dependencies for integrated plugin, using this version as a "recommended" dependencies would result in obsolete installations.
Jenkins plugin manager only do support `latest`, so script is consistent with this behavior.
For people who want a reproducible installation, I recommend to shrink-wrap the whole list of installed plugins into a (long) `plugins.txt` file.

**Comment by ndeloof** [comment]
👎

**Comment by daniel-beck** [comment]
@ndeloof Don't know whether you were present in the discussion, but this conflict between reproducibility and keeping things updated came up a week ago with @jglick favoring one approach, @oleg-nenashev the other, in setting up their demo instances. I'm not saying this shouldn't be supported, but it probably shouldn't be made the default for the less detail-oriented users. That's as far as I'm willing to voice an uninformed opinion on this :-)

Also, regarding the implementation, it looks like if you have two plugins depending on the same third plugin, and the first depends on an older version, the second plugin won't update the dependency to its minimum (`doDownload`), resulting in a broken configuration with unloadable plugins. (From reading the code only, so it's unconfirmed.)

**Comment by ndeloof** [comment]
a bash script is probably not the best place to implement a clever dependency solver. This one should be kept simple and stupid, and let user either fix it with more explicit dependencies, or just fix them all with a full list of what is expected on installation.

**Comment by ndeloof** [comment]
I wish we could just invoke `PluginManager` form command line with some special `java -jar jenkins.war` mode, so getting the plugins populated would rely on the exact same code as a live jenkins instance ... and we can then fix it on a single place :P

**Comment by oleg-nenashev** [comment]
@ndeloof Well, you can do it via System Groovy Hook scrips :)

> Don't know whether you were present in the discussion, but this conflict between reproducibility and keeping things updated came up a week ago with @jglick favoring one approach, @oleg-nenashev 

I do not recall such conflict. I and @jglick demoed approaches with the different **default** dependency resolution behavior (fixed version in his case, latest in mine). But I would be using fixed resolution on production as well. It's possible via plugins.txt, though for better UX it should have a flag for disabling dependency resolution (but checking dependencies during Docker build).

So generally I support the behavior offered by @fly2wind as an opt-in feature. But I do not feel it should be a default one, because it will probably cause some breaking changes for people updating images (or just using `latest`)

**Comment by MarkEWaite** [comment]
Closing this pull request because the Docker image now includes plugin installation manager tool that provides better dependency management.  The install-plugins.sh script will be deprecated soon.

**Pull request closed without merging**
