### PR TITLE
Created an automated flow for updating of plugin manager cli (#1200)

### PR DESCRIPTION
**Pull request by R3dIO**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
     I have added a GitHub action workflow that will run periodically and update the version of plugin-cli in docker-bake file
- [x] Link to relevant issues in GitHub or Jira
      Fixes https://github.com/jenkinsci/docker/issues/1200
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fix the issue
       As its a workflow it could be only tested on Github

### CODE REVIEW

**Comment by timja** [comment]
Have you tried this in your fork? It looks good from reading through it though

**Comment by R3dIO** [comment]
Yes I tried it but it was failing on the git token part where. I think it need a fully configured action.

**Comment by oleg-nenashev** [comment]
It looks reasonable though I am not sure we want to maintain an extra dependency update from in addition to Dependabot and UpdateCLI. None of them would work for this use-case OOTB, but maybe we are at the point when it makes sense to introduces a Bill Of Materials pom.xml in this repo

**Review by timja — APPROVED** [review]
Let's give it a go, it's the same method as in bom which pre-dates update cli

**Pull request merged**
