### PR TITLE
demo how to start jenkins with jnlp /computer/slave1 that has docker and docker-compose

### PR DESCRIPTION
**Pull request by vvitayau**
Demonstrate how to demo jenkins with a simple jnlp slave based on java:8u45 via
``docker-compose -f slave/jdk8u45/docker-compose.yml [rm | build | up | ps | stop]``

And how to organize additional other jnlp slave like with with docker and docker-compose included via
 `` docker-compose -f slave/docker/docker-compose.yml [rm | build | up | ps | stop]``

### CODE REVIEW

**Comment by vvitayau** [comment]
I realize this is a demo on how to organize the directory. 
So I feel merging this is appropriate for the community ... 
since others may fork the main repo to make their own custom changes.

This PR gives the community guidance on how to define different type of JNLP slaves.

**Comment by ndeloof** [comment]
You probably will be interested in https://github.com/jenkinsci/docker-jnlp-slave

**Comment by vvitayau** [comment]
I prefer to get slave.jar from jenkins master

**Comment by ndeloof** [comment]
I don't understand well this PR goal. If you propose this as a documentation helper, please add some README.md plain text explanations on the proposed architecture.

**Pull request closed without merging**
