### PR TITLE
Switch to recommended approach for certificates

### PR DESCRIPTION
**Pull request by timja**
see also https://github.com/jenkinsci/winstone/pull/232

### CODE REVIEW

**Review by basil — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]

**Review by basil — COMMENTED** [review]
Sorry, I did not review this carefully enough the first time. Do we not also need to remove the `COPY` directives above this line? I think we do, because they seem to only exist in order to supply the values for the flags that we are removing from this PR.

**Review by dduportal — CHANGES_REQUESTED** [review]
Same as @basil feedback: it looks like that the 2 `COPY` instructions have to be removed.

At first superficial glance, the files `https.pem` and `https.key` should also be removed from the repository.

**Comment by timja** [comment]
> At first superficial glance, the files `https.pem` and `https.key` should also be removed from the repository.

they aren't in the repo as far as I can tell, it's an example for how people can configure Jenkins

**Review by dduportal — APPROVED** [review]
LGTM, thanks for the explanation!

**Pull request merged**
