### PR TITLE
Fix curl options

### PR DESCRIPTION
**Pull request by HeyLazySunnyKid**
Fix curl requests with custom curl options

### CODE REVIEW

**Comment by MarkEWaite** [comment]
The `install-plugins.sh` script is about to be deprecated.  It was a reasonable approximation when all we could use for downloads was either Jenkins core or a shell script.  Now we have the plugin manager CLI that is included in the Docker image as a preview.  I'd rather not change the curl options in a script that will be deprecated soon.

@slide do you have a strong preference on this one?

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
I'm requesting changes as a way to remind myself that this should not be merged until further discussions occur with other maintainers of the Docker images.

**Comment by slide** [comment]
Do we have a timeline for deprecation? If we're not planning on deprecating soon, this might be good to pull in.

**Comment by MarkEWaite** [comment]
> Do we have a timeline for deprecation? If we're not planning on deprecating soon, this might be good to pull in.

I don't have a timeline for deprecation.  I don't object to this pull request, though I'm not clear how the `--show-error` option (`-S`) and the `--fail` option (`-f`) will interact with one another.

The `--fail` argument is described as:

>  -f, --fail          Fail silently (no output at all) on HTTP errors (H)

The `--show-error` argument is described as:

>  -S, --show-error    Show error. With -s, make curl show errors when they occur

Those descriptions seem to be contradictory.  When curl detects an HTTP error, will the command fail with no output at all or will it show an error when it occurs?  Is the order of arguments significant in the curl command?

The `curl` man page for [Debian stretch](https://manpages.debian.org/stretch/curl/curl.1.en.html) provides more details for that operating system, but I'm still not certain how those arguments will be interpreted.

The `--fail` description:

>-f, --fail
> (HTTP) Fail silently (no output at all) on server errors. This is mostly done to better enable scripts etc to better deal with failed attempts. In normal cases when an HTTP server fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag will prevent curl from outputting that and return error 22.
>
> This method is not fail-safe and there are occasions where non-successful response codes will slip through, especially when authentication is involved (response codes 401 and 407).

The `--show-error` description:

> -S, --show-error
> When used with -s, --silent, it makes curl show an error message if it fails.

Based on that, I assume that `--show-errors` will "win" and the curl command will now show error messages when it fails.  When it fails, the curl command will return error 22 rather than returning success and writing the contents of the error page.

**Comment by HeyLazySunnyKid** [comment]
I suggest passing curl parameters via env variable CURL_OPTIONS  in both usages of curl in this script to avoid hard coding them. The “-sSfL” default parameters were taken from current plugin-download.sh code [script](https://github.com/jenkinsci/docker/blob/ae762bf957619ff94526296affc355cf3d75ea00/install-plugins.sh#L112) and  [head](https://github.com/jenkinsci/docker/blob/ae762bf957619ff94526296affc355cf3d75ea00/install-plugins.sh#L15) .

**Review by slide — APPROVED** [review]
I think this change is fine. It aligns the invocations of curl to use the same options.

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
