### PR TITLE
Use plugin installation manager 2.8.0

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Use plugin installation manager 2.8.0

Will need to enable dependabot on this repository since the plugin installation manager is now using continuous delivery from JEP-229.

### CODE REVIEW

**Comment by garethjevans** [comment]
I don't think dependabot will be able to update this, but updatecli should be able to update an ARG/ENV within the docker file based on a maven release.

**Review by garethjevans — APPROVED** [review]

**Comment by slide** [comment]
It would be nice if we could just have an env file that is pulled in during the build and only update this in one place. I'll look at doing something like that (it would require us to build and publish completely on our infra instead of using docker hub, but we've talked about doing that anyway).

**Comment by rbjorklin** [comment]
How long does it usually take for these type of changes to land in docker hub?

```
❯ docker pull jenkins/jenkins:2.263.4-lts-jdk11

❯ docker inspect --format '{{ .RepoDigests}}' jenkins/jenkins:2.263.4-lts-jdk11
[jenkins/jenkins@sha256:2c4f7e27a2fb0715c3f45dfbdcfaba57bbeafe50da678cf062e27f790ab39738]

❯ docker run --rm -ti --entrypoint /bin/bash jenkins/jenkins:2.263.4-lts-jdk11 -c 'java -jar /usr/lib/jenkins-plugin-manager.jar --version'
2.2.0
```

**Comment by MarkEWaite** [comment]
> How long does it usually take for these type of changes to land in docker hub?

Won't land until the next Jenkins release.  Weekly Jenkins 2.283 will include this change and stable (LTS) Jenkins 2.277.1 will include this change when they are released next week.

**Pull request merged**
