### PR TITLE
Adding support for amazonlinux

### PR DESCRIPTION
**Pull request by dave-juicelabs**
Adding this here because I know there is more work to support this but I do not know what that might be. As a result, I have not followed any of the procedures below but wanted to make this available if someone was willing to fully support amazonlinux.

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by dave-juicelabs** [comment]
Feel free to close, remove, etc.

**Comment by dduportal** [comment]
Hi @dave-juicelabs , thanks for raising the issue.

Could you describe the problem you would want to solve by adding this OS?

As a general idea, we would want to decrease the amount of supported OS in the controller image as the whole idea of providing a container image is to abstract the OS. Ideally, we should not have any OS at all inside the image (look at examples such as Nix or https://github.com/wolfi-dev/os).
Adding a lot of OS increases the amount of scenarios to support which is the absolute opposite of the problem solved by containers (this is a NP matrix problem which makes sense for packages or acceptance testing for Jenkisn of course).

I might be missing a point of course (I do not have absolute knowledge), hence my question about your use case.

Adding a new OS would make sense, though, for the agent images: a standard usage of Jenkins means adding the toolins in the agents so it would be really useful for end users with Amazon Linux tooling for instance.


This comment is neither an approval or a refusal: it is a request for clarification to ensure that if this PR is merged, then all the safety nets for having it sustainable are ok.

**Comment by MarkEWaite** [comment]
I think that we should not add support for Amazon Linux 2 in the Jenkins container images.  I've seen no requests from other users asking that the container image be based on Amazon Linux 2 and I've not seen indications from the submitter of this pull request that they are willing to remain actively involved in the maintenance of the container images after this is merged.  Without active maintainers to care for the Amazon Linux container image, it takes more time from the current maintainers without providing significant benefit to container users.

I consider Amazon Linux 2 to be on "extended life support".  Amazon had announced an end of life date for Amazon Linux 2 in favor of the upcoming release of Amazon Linux 2022, Amazon has extended that end of life date for Amazon Linux 2 on two different occasions.  They have stated that they intend to release Amazon Linux 2022 this year and to end support for Amazon Linux 2022 in 2024.

I feel that we already have more operating system variants than is healthy for us to support.  In my opinion, adding more operating system variants to the mix is increasing the maintainer burden without increasing the number of maintainers.  I think that's the wrong direction for our container images.

If the submitter is willing to be actively involved in maintaining and improving the container image definitions in this repository, that would reduce my concerns about that aspect of adding this container to the list of containers.  It would not completely eliminate it, since this is the first submission from @dave-juicelabs , but it would reduce my concerns.  

@dave-juicelabs is this a one-time donation pull request or is this the beginning of a series of contributions to the maintenance of the Jenkins container image?  Either is fine and we're grateful for contributions, but if you don't plan to be an ongoing contributor to this repository then I'm of the opinion that we should not accept this contribution.

**Comment by MarkEWaite** [comment]
Closing this pull request on the assumption that it was a single contribution.  Thanks!

**Pull request closed without merging**
