### PR TITLE
chore(tests) set curl to verbose to help diagnosing download errors

### PR DESCRIPTION
**Pull request by dduportal**
This PR is an attempt to correct the error `curl: (16) Error in the HTTP2 framing layer` which happen quite often making the test for install-plugin to fail.

### CODE REVIEW

**Comment by dduportal** [comment]
First step on this draft: setting up the `CURL_OPTS` to the same as default appended with `--verbose` to see what are the detailed errors.
The goal is to make sure that there is not a misconfiguration in our Apache servers for updates.jenkins.io / Nginx ingress for get.jenkins.io.

Ref.
- https://github.com/curl/curl/issues/3750
- https://curl.se/mail/archive-2019-06/0006.html

**Comment by dduportal** [comment]
So we got the following (curl) error: 

```console
[2022-06-25T15:33:12.609Z] #   *   Trying 52.202.51.185:443...
[2022-06-25T15:33:12.609Z] #   * Connected to updates.jenkins.io (52.202.51.185) port 443 (#0)
[2022-06-25T15:33:12.609Z] #   * ALPN: offers h2
[2022-06-25T15:33:12.609Z] #   * ALPN: offers http/1.1
[2022-06-25T15:33:12.609Z] #   *  CAfile: /etc/ssl/certs/ca-certificates.crt
[2022-06-25T15:33:12.609Z] #   *  CApath: none
[2022-06-25T15:33:12.609Z] #   } [5 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (OUT), TLS handshake, Client hello (1):
[2022-06-25T15:33:12.609Z] #   } [512 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Server hello (2):
[2022-06-25T15:33:12.609Z] #   { [122 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
[2022-06-25T15:33:12.609Z] #   { [19 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Certificate (11):
[2022-06-25T15:33:12.609Z] #   { [4036 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, CERT verify (15):
[2022-06-25T15:33:12.609Z] #   { [264 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Finished (20):
[2022-06-25T15:33:12.609Z] #   { [52 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
[2022-06-25T15:33:12.609Z] #   } [1 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (OUT), TLS handshake, Finished (20):
[2022-06-25T15:33:12.609Z] #   } [52 bytes data]
[2022-06-25T15:33:12.609Z] #   * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
[2022-06-25T15:33:12.609Z] #   * ALPN: server accepted h2
[2022-06-25T15:33:12.609Z] #   * Server certificate:
[2022-06-25T15:33:12.609Z] #   *  subject: CN=updates.jenkins.io
[2022-06-25T15:33:12.609Z] #   *  start date: Jun 13 22:47:28 2022 GMT
[2022-06-25T15:33:12.609Z] #   *  expire date: Sep 11 22:47:27 2022 GMT
[2022-06-25T15:33:12.609Z] #   *  subjectAltName: host "updates.jenkins.io" matched cert's "updates.jenkins.io"
[2022-06-25T15:33:12.609Z] #   *  issuer: C=US; O=Let's Encrypt; CN=R3
[2022-06-25T15:33:12.609Z] #   *  SSL certificate verify ok.
[2022-06-25T15:33:12.609Z] #   * Using HTTP2, server supports multiplexing
[2022-06-25T15:33:12.609Z] #   * Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
[2022-06-25T15:33:12.609Z] #   } [5 bytes data]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:method: GET]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:path: /update-center.json?version=2.303]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:scheme: https]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:authority: updates.jenkins.io]
[2022-06-25T15:33:12.609Z] #   * h2h3 [user-agent: curl/7.83.1]
[2022-06-25T15:33:12.609Z] #   * h2h3 [accept: */*]
[2022-06-25T15:33:12.609Z] #   * Using Stream ID: 1 (easy handle 0x7f8cb99881b0)
[2022-06-25T15:33:12.609Z] #   } [5 bytes data]
[2022-06-25T15:33:12.609Z] #   > GET /update-center.json?version=2.303 HTTP/2
[2022-06-25T15:33:12.609Z] #   > Host: updates.jenkins.io
[2022-06-25T15:33:12.609Z] #   > user-agent: curl/7.83.1
[2022-06-25T15:33:12.609Z] #   > accept: */*
[2022-06-25T15:33:12.609Z] #   > 
[2022-06-25T15:33:12.609Z] #   { [5 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[2022-06-25T15:33:12.609Z] #   { [281 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
[2022-06-25T15:33:12.609Z] #   { [281 bytes data]
[2022-06-25T15:33:12.609Z] #   * old SSL session ID is stale, removing
[2022-06-25T15:33:12.609Z] #   { [5 bytes data]
[2022-06-25T15:33:12.609Z] #   < HTTP/2 302 
[2022-06-25T15:33:12.609Z] #   < date: Sat, 25 Jun 2022 15:33:06 GMT
[2022-06-25T15:33:12.609Z] #   < server: Apache
[2022-06-25T15:33:12.609Z] #   < location: https://updates.jenkins.io/dynamic-2.303/update-center.json
[2022-06-25T15:33:12.609Z] #   < content-length: 243
[2022-06-25T15:33:12.609Z] #   < content-type: text/html; charset=iso-8859-1
[2022-06-25T15:33:12.609Z] #   < 
[2022-06-25T15:33:12.609Z] #   * Ignoring the response-body
[2022-06-25T15:33:12.609Z] #   { [243 bytes data]
[2022-06-25T15:33:12.609Z] #   * Connection #0 to host updates.jenkins.io left intact
[2022-06-25T15:33:12.609Z] #   * Issue another request to this URL: 'https://updates.jenkins.io/dynamic-2.303/update-center.json'
[2022-06-25T15:33:12.609Z] #   * Found bundle for host: 0x55634b29e640 [can multiplex]
[2022-06-25T15:33:12.609Z] #   * Re-using existing connection #0 with host updates.jenkins.io
[2022-06-25T15:33:12.609Z] #   * Connected to updates.jenkins.io (52.202.51.185) port 443 (#0)
[2022-06-25T15:33:12.609Z] #   * h2h3 [:method: GET]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:path: /dynamic-2.303/update-center.json]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:scheme: https]
[2022-06-25T15:33:12.609Z] #   * h2h3 [:authority: updates.jenkins.io]
[2022-06-25T15:33:12.609Z] #   * h2h3 [user-agent: curl/7.83.1]
[2022-06-25T15:33:12.609Z] #   * h2h3 [accept: */*]
[2022-06-25T15:33:12.609Z] #   * Using Stream ID: 3 (easy handle 0x7f8cb99881b0)
[2022-06-25T15:33:12.609Z] #   } [5 bytes data]
[2022-06-25T15:33:12.609Z] #   > GET /dynamic-2.303/update-center.json HTTP/2
[2022-06-25T15:33:12.609Z] #   > Host: updates.jenkins.io
[2022-06-25T15:33:12.609Z] #   > user-agent: curl/7.83.1
[2022-06-25T15:33:12.609Z] #   > accept: */*
[2022-06-25T15:33:12.609Z] #   > 
[2022-06-25T15:33:12.609Z] #   { [5 bytes data]
[2022-06-25T15:33:12.609Z] #   * Closing connection 0
[2022-06-25T15:33:12.609Z] #   { [5 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (IN), TLS alert, close notify (256):
[2022-06-25T15:33:12.609Z] #   { [2 bytes data]
[2022-06-25T15:33:12.609Z] #   * TLSv1.3 (OUT), TLS alert, close notify (256):
[2022-06-25T15:33:12.609Z] #   } [2 bytes data]
[2022-06-25T15:33:12.609Z] #   curl: (16) Error in the HTTP2 framing layer
```

which sounds like the remote webserver (Apache on updates.jenkins.io) seems to close the HTTP/2 stream. Seems like https://github.com/curl/curl/issues/3750#issuecomment-482155584

**Comment by dduportal** [comment]
=> https://bugzilla.redhat.com/show_bug.cgi?id=1690971 🤔

**Comment by timja** [comment]
> which sounds like the remote webserver (Apache on updates.jenkins.io) seems to close the HTTP/2 stream. Seems like https://github.com/curl/curl/issues/3750#issuecomment-482155584

if that's the issue it was fixed in curl 7.65

**Comment by dduportal** [comment]
> > which sounds like the remote webserver (Apache on updates.jenkins.io) seems to close the HTTP/2 stream. Seems like [curl/curl#3750 (comment)](https://github.com/curl/curl/issues/3750#issuecomment-482155584)
> 
> if that's the issue it was fixed in curl 7.65

😅 the « fix » is that curl now prints a correct error message, which is the reason of the verbose flag : it prints the « real » error that happens when the HTTP/2 stream is reused during a redirection to the same server (which happens : update center initial URL redirects to /dynamic/). The TLS négociation fails, and the server cuts the connection. 

There are multiple factors involved here, the main issue being Apache2 with an old version (because the VM is still ubuntu 18.04). We plan to bump to 20.04 (even 22.04) when migrating to Oracle cloud for the update-center, but we still have the test harness problem here. 
The current road being tried here is to force http1.1 to keep the test.

it leads to another « tricky » issue: curl is old as hell on centos image, so I had to hack 😅

finally, the pertinence to even test install-plugin at all is to be questionned. Bit it appears that there are other errors that happens, that still are caused by curl 😭

**Comment by timja** [comment]
What are the other errors? We can do something about install-plugins

**Comment by timja** [comment]
see https://github.com/jenkinsci/docker/pull/1408 for removing install-plugins.sh

**Comment by dduportal** [comment]
> What are the other errors? We can do something about install-plugins

Other errors were usually anywhere in the test harness, related to a docker image not found when doing while it hsould exist because `docker_build_child()` function was called right before. However, it feels like that this errors always happened when there was a rate limit.

Closing in favor of #1408 . I'll reopen to investigate if these other errors appears after #1408 is merged.

**Pull request closed without merging**
