### PR TITLE
fix(helpdesk-3099) ensure that missing 2.346.x (jdk8 and jdk17-preview) images are published

### PR DESCRIPTION
**Pull request by dduportal**
Ref. https://github.com/jenkins-infra/helpdesk/issues/3099

This PR introduces the following changes:

- Bump jenkins plugin CLI to `2.12.8`, because it's the version used on the current 2.346.2 and 2.346.3 published images from the `master` branch:

```console
docker git:(fix/missing-2.346.x-images) ✗ docker run --rm --entrypoint=jenkins-plugin-cli jenkins/jenkins:2.346.1-lts-jdk11 --version
2.12.6
➜  docker git:(fix/missing-2.346.x-images) ✗ docker run --rm --entrypoint=jenkins-plugin-cli jenkins/jenkins:2.346.2-lts-jdk11 --version
2.12.8
➜  docker git:(fix/missing-2.346.x-images) ✗ docker run --rm --entrypoint=jenkins-plugin-cli jenkins/jenkins:2.346.3-lts-jdk11 --version
2.12.8
```

=> but only for JDK17 and JDK11. For JDK8, we are using 2.17.2, which is the latest version supported.

- Linux images: 
  - Ensure that *only* the `2.346.x` are checked by the publication script

    ```console
    $ bash ./.ci/publish.sh -n
    Docker repository in Use:
    * JENKINS_REPO: jenkins/jenkins
    Dry run, will not publish images
    Tag is already published: 2.346.1
    WARNING: could not get a valid manifest at the URL https://index.docker.io/v2/jenkins/jenkins/manifests/2.346.2-alpine-jdk17-preview.
      (For debugging purposes) manifest={"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":"unknown tag=2.346.2-alpine-jdk17-preview"}]}
    2.346.2 not published yet
    Version 2.346.2 higher than 1.0: publishing 2.346.2 latest_weekly:false latest_lts:false
    WARNING: could not get a valid manifest at the URL https://index.docker.io/v2/jenkins/jenkins/manifests/2.346.3-alpine-jdk17-preview.
      (For debugging purposes) manifest={"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":"unknown tag=2.346.3-alpine-jdk17-preview"}]}
    2.346.3 not published yet
    Version 2.346.3 higher than 1.0: publishing 2.346.3 latest_weekly:false latest_lts:true
    ```

  - Ensure that no jdk11 version is built (to avoid overriding images already published)

- Cherry-picks from `master`:
  - Bumped JDK17 (to use the same as other 2.346.x published images)
  - Fixed build tooling (test harness, test tools, linter fixes on Dockerfile)
  - Bumped the OS images (debian/alpine)
  - https://github.com/jenkinsci/docker/pull/1435 fix on the jenkins startrup script for Windows images

- Bumped JDK8 to latest available to benefit from last changes

(edit)
* It should only build and test JDK8 images on public CI
* It should only publish:
  * JDK8 images by building and publishing as usual
  * JDK17 "preview" images by copying from their already existing JDK17 images: same shasum to avoid surprises (instead of rebuilding it there), hence fulfilling the "least surprise" principle.

### CODE REVIEW

**Comment by dduportal** [comment]
There are still test error with the JDK17, when passing custom JVM_OPTS or JENKINS_..._OPTS option.

**Review by basil — COMMENTED** [review]
I think the test errors you're seeing were fixed on the main branch in #1409 and/or #1411.

**Comment by dduportal** [comment]
> I think the test errors you're seeing were fixed on the main branch in #1409 and/or #1411.

Thanks @basil ! Given the temporary character of this branch (that should be used a few times for publication), I've adapted the behavior:

- It should only build and test JDK8 images on public CI
- It should only publish:
  - JDK8 images  by building and publishing as usual
  - JDK17 "preview" images by copying from their already existing JDK17 images: same shasum to avoid surprises (instead of rebuilding it there), hence fulfilling the "least surprise" principle.
  
  
WDYT folks?

**Review by NotMyFault — APPROVED** [review]

**Review by timja — APPROVED** [review]

**Review by basil — APPROVED** [review]
Looks good to me!

**Pull request merged**
