### PR TITLE
Use Alpine Linux 3.18.4, not 3.18.3

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Use Alpine Linux 3.18.4, not 3.18.3

Released a few days ago, passes tests in platformlabeler.

### Testing done

Ran tests on Linux.

@gounthar I was surprised that this upgrade was not detected by dependabot and was not detected by updatecli.  Will the Alpine operating system version upgrades be detected in a future updatecli definition or should base operating system upgrade detection happen in some other way?

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by gounthar** [comment]
Alpine is not yet tracked in this repo, Mark, at least with `[updatecli](https://github.com/jenkinsci/docker/tree/master/updatecli/updatecli.d)`.

As for [dependabot](https://github.com/jenkinsci/docker/blob/master/.github/dependabot.yml#L8), I think the only reason is it is run on a weekly basis...

**Review by gounthar — APPROVED** [review]
Thank you, Mark!

**Comment by MarkEWaite** [comment]
> As for [dependabot](https://github.com/jenkinsci/docker/blob/master/.github/dependabot.yml#L8), I think the only reason is it is run on a weekly basis... It could run a few days from now. 🤔

Thanks.  I ran dependabot a few minutes before creating this pull request because I assumed it would detect the upgrade.  It didn't detect it.  I guess dependabot only works with `FROM` and not with `ARG`.

Would it be difficult to add Alpine version tracking to the updatecli definitions?

**Review by timja — APPROVED** [review]

**Comment by gounthar** [comment]
> Thanks. I ran dependabot a few minutes before creating this pull request because I assumed it would detect the upgrade. It didn't detect it. I guess dependabot only works with `FROM` and not with `ARG`.
My bad! Your guess is 💯 true. Dependabot can't handle `ARG` updates.

> Would it be difficult to add Alpine version tracking to the updatecli definitions?
Nope, easy breezy, lemon squeezy. 😊

**Comment by gounthar** [comment]
Please have a look at #1727 .

**Pull request merged**
