### PR TITLE
[INFRA-2754] Stop downloading from incrementals repo in test

### PR DESCRIPTION
**Pull request by jglick**
Amends #694. Found by @daniel-beck.

### CODE REVIEW

**Comment by daniel-beck** [comment]
This incremental gets downloaded hundreds of times every day, so far >300k times in the ~2.5 years it existed, resulting in >100GB of traffic.

**Comment by jglick** [comment]
Did you mean to link to [INFRA-2821](https://issues.jenkins.io/browse/INFRA-2821) instead?

**Comment by daniel-beck** [comment]
INFRA-2754 is more epic 💪😄

**Review by oleg-nenashev — APPROVED** [review]
Taking the traffic, I am +1. Make sure that plugin installation manager has not similar tests

**Comment by daniel-beck** [comment]
> Make sure that plugin installation manager has not similar tests

As long as tests are only run when being built, should be fine, as that's not what everyone everywhere does. Building Docker images though…?

**Review by timja — APPROVED** [review]

**Comment by slide** [comment]
We'd want this removed as well:

https://github.com/jenkinsci/docker/blob/master/tests/plugins-cli/pluginsfile/plugins.txt#L24

**Review by olblak — APPROVED** [review]

**Pull request merged**
