### PR TITLE
Publish under "jenkins" dockerhub organization

### PR DESCRIPTION
**Pull request by ndeloof**
see https://github.com/jenkinsci/docker/issues/515

### CODE REVIEW

**Comment by carlossg** [comment]
do we want to push to both for a while? or how is the migration happening ?

**Comment by ndeloof** [comment]
I'd prefer we make it clear `jenkinsci/*` as well as official `jenkins` are deprecated.
we for sure can push both, but this will just postpone this deprecation (and maybe add extra confusion ?)

**Comment by carlossg** [comment]
then the README needs to change too

**Comment by ndeloof** [comment]
@rtyler please do. And let me know if anything goes wrong

**Comment by rtyler** [comment]
@ndeloof looks like jenkins/jenkins now has some tags, can you target this change to the alpine branch too?

**Comment by ndeloof** [comment]
@rtyler see https://github.com/jenkinsci/docker/pull/532

**Pull request merged**
