### PR TITLE
chore(publish) fix multi-arch publication check (jenkins-infra/helpdesk/issues/2890)

### PR DESCRIPTION
**Pull request by dduportal**
### Description

This PR is related to jenkins-infra/helpdesk/issues/2890.

It fixes the publication script to ensure that all images declinations and Linux CPU architectures are checked for a given tag.

Once merged, this PR will rebuild and republish all the images for the following tags:

```
2.319.1
2.319.2
2.319.3
2.320
2.321
2.322
2.323
2.324
2.325
2.326
2.327
2.328
2.329
2.330
2.331
2.332
2.332.1
2.332.2
2.333
2.334
2.335
2.336
2.337
2.338
2.339
2.340
2.341
2.342
2.343
2.344
```

and also for `lts` + `weekly`

=> The rationale is that these tags all have at least 1 image that was re-published by the "quickstart" branch job (as per https://github.com/jenkins-infra/helpdesk/issues/2890#issuecomment-1104201895), leading to an outdated Docker image manifest (`application/vnd.oci.image.index.v1+json` wrapped under an `application/vnd.docker.distribution.manifest.v2+json` enveloppe, instead of an `application/vnd.docker.distribution.manifest.list.v2+json` which support multiple CPU architectures).
So we have to republish all of them now.

### Testing

Running the script locally with the flag `-n` (dry run) led to a full docker buildx rebuil of ALL these tags. Means that the script works at least partially.

### Check List

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
I think you're proposing the best path forward.  The container images that were originally written by the weekly and LTS build processes have already been overwritten by the build from the "quickstart" branch.  We can't undo that change.  Since we can't undo that change, we're best served by running the build to update those images from the master branch.

**Review by MarkEWaite — APPROVED** [review]
I executed many of the steps interactively from my Ubuntu 20.04 desktop machine with Docker installed and the results were as expected.  I believe this is ready to go.

I think we may want to delay the republish until Monday so that we're not doing it at the end of a day before the start of the weekend.  The `quickstart` damage is already done and making it wait a few more days to be repaired is not a huge risk.

**Review by timja — APPROVED** [review]

**Comment by dduportal** [comment]
Let's wait for Monday 25 then 👍

**Comment by dduportal** [comment]
@timja @MarkEWaite I'm ready for this to be merged (trusted.ci is in good shape, I'll monitor)

**Pull request merged**
