### PR TITLE
Upgrade tini to 0.16.1

### PR DESCRIPTION
**Pull request by damienbeaufils**
This PR upgrades Tini to the last version.

### CODE REVIEW

**Comment by damienbeaufils** [comment]
@oleg-nenashev No particular feature, it is just to benefit from Tini new arches (and to use a up-to-date dependency)

**Comment by carlossg** [comment]
we are trying to install tini from a package in #579 for alpine multiarch

**Comment by Fantoccini** [comment]
👍 for this as it enables armel arch build.

**Comment by carlossg** [comment]
latest alpine uses 0.16.1 so I've merged the master changes for all the variants to use the same

**Comment by Fantoccini** [comment]
Seems the only issue is the unstable key server:

https://ci.jenkins.io/blue/organizations/jenkins/Packaging%2Fdocker/activity?branch=PR-599

There are few success builds.

**Comment by dbsanfte** [comment]
Looks like something in this branch moved the executable from /bin/tini to /sbin/tini within the image. This has broken a lot of people's startup scripts I bet.

**Pull request merged**
