### PR TITLE
Always upgrade plugins if PLUGINS_FORCE_UPGRADE=true

### PR DESCRIPTION
**Pull request by Triqqo**
For specific cases where you may want to upgrade a plugin manually once, while still wanting to receive future updates via the image.

### CODE REVIEW

**Comment by carlossg** [comment]
Fixes #741

**Comment by hibbert** [comment]
Hi,

I'm wandering when this will find its way into a tag pushed to docker hub? (https://hub.docker.com/r/jenkins/jenkins/tags?page=1), I've checked the lts tag created 2 hours ago today and /usr/local/bin/jenkins-support does not seem to be the merged version

Thanks

**Comment by carlossg** [comment]
I don't know why lts shows as updated but it's 2.164.2 published a month ago

```
Images 2.164.2 [sha256:15625611d6fbe71aa7ef24f6681a4ccab82893a71514546ca0c10cc43e5adb69] and lts [sha256:15625611d6fbe71aa7ef24f6681a4ccab82893a71514546ca0c10cc43e5adb69] are already the same, not updating tags
```

**Comment by hibbert** [comment]
Ah okay. I've checked jenkins/jenkins:latest and the changes are in there. So I'd guess this will make it's way into the lts version when a new jenkins lts is available

**Pull request merged**
